#---------------------
# 注意修改内存配置
# 注意修改VIP地址
#---------------------

# 离线文件安装包所在目录-----------------------------------------------------------------------
package_dir: '/data01/package'
ntp_server_addr: '192.168.160.59'
yum_base_url: 'http://192.168.161.202/yum/'

## harbor----------------------------------------------------------------------------------
# harbor主备vip
harbor_keepalived_vip: 192.168.160.47
harbor_port: '8888'
harbor_keepalived_virtual_router_id: '47'
harbor_keepalived_vrrp_instance_interface: eth0
harbor_root_dir: '/data01/harbor'
# harbor压缩包
harbor_tar: '{{ package_dir }}/harbor/harbor.tar.gz'
harbor_password: 'admin123Admin'
# harbor安装数据目录
harbor_data_volume: '{{ harbor_root_dir }}/harbor-data'

# docker-----------------------------------------------------------------------------------
# harbor私服地址
image_repository: '{{ harbor_keepalived_vip }}:{{ harbor_port }}'
#docker insecure registry，可能有多个，用harbor地址就可以了
docker_insecure_registries:
  - '{{ image_repository }}'
# docker数据目录
docker_data_root: '/data01/docker'

# nginx---------------------------------------------------------------------------------------
# Nginx 数据目录
nginx_root_dir: '/data01/nginx'
nginx_keepalived_vip: 192.168.160.5
nginx_keepalived_virtual_router_id: '5'
nginx_keepalived_vrrp_instance_interface: eth0

# es----------------------------------------------------------------------------------------
# es数据盘
es_root_dir: '/data01/es'
# es集群名
es_cluster_name: 'es-practice-cluster-7.3.2'
# es jvm信息
es_java_opts: '-Xms8G -Xmx8G'
es_clear_at_day: 20
es_clear_month_ago: 3
es_log_replicas: 1
es_log_shards: 60

# kafka---------------------------------------------------------------------------------------
# kafka数据目录
kafka_root_dir: '/data01/kafka'
# kafka jvm信息
kafka_heap_opts: '-Xmx2G -Xms1G'

# roketmq------------------------------------------------------------------------------------
jdk_dir: '/data01/jdk1.8.0_202'
rocketmq_root_dir: '/data01/rocketmq'
rocketmq_package_dir: '{{ package_dir }}/rocketmq'
rocketmq_user: 'rocketmq'
rocketmq_user_pass: 'rocketmq123'

# ravencast-----------------------------------------------------------------------------------
ravencast_xms_xmx_args: '-Xms2G -Xmx8G'
ravencast_root_dir: '/data01/ravencast'

# k8s-----------------------------------------------------------------------------------------
k8s_keepalived_vip: 192.168.160.78
k8s_keepalived_virtual_router_id: '78'
k8s_keepalived_vrrp_instance_interface: eth0
control_plane_endpoint: '{{ k8s_keepalived_vip }}:6443'
pod_network_cidr: '10.244.0.0/16'
component_manifest_dir: '/data01/kube-manifest'
elk_manifest_root_dir: '{{ component_manifest_dir }}/elk'
kube_component_file: '{{ component_manifest_dir }}/kube-component.md'
etcd_backup_root_dir: '/data01/etcd-backup'

# monitor--------------------------------------------------------------------------------------
nfs_root_dir: '/data01'
nfs_server: "{{ groups['nas'][0] }}"
monitor_nfs_path: '{{ nfs_root_dir }}/monitoring'
monitor_manifest_root_dir: '{{ component_manifest_dir }}/monitoring'
prometheus_storage: '50Gi'
prometheus_data_retention: '35d'
grafana_storage: '50Gi'
alertmanager_storage: '20Gi'
alertmanager_data_retention: '120h'
alertmanager_smtp_server: 192.168.160.1:587
alertmanager_smtp_from: mouyongde@huawei.com
alertmanager_smtp_username: mouyongde@huawei.com
alertmanager_smtp_password: Huawei@777.com
alertmanager_email_to: tangjizhou@huawei.com
node_exporter_root_dir: /data01/node-exporter
process_exporter_root_dir: /data01/process-exporter

# redis---------------------------------------------------------------------------------------
redis_data_dir: '/data01/redis'
#32G大小的3/4
redis_maxmemory: '{{ 10|int * 1024|int * 1024|int * 1024|int }}'