image_repository: '192.168.160.47:8888'
# docker
docker_insecure_registries:
  - 'xcz'
docker_data_root: '/data01/docker'

## harbor
harbor_keepalived_vip: 192.168.160.39
harbor_keepalived_virtual_router_id: '66'
harbor_keepalived_vrrp_instance_interface: eth0
harbor_tar: '/etc/ansible/package/harbor_20210809.tar.gz'
harbor_root_dir: '/data01/harbor'
harbor_hostname: '192.168.160.39'
harbor_port: '80'
harbor_password: 'admin123Admin'
harbor_data_volume: '{{ harbor_root_dir }}/harbor-data'

# nginx todo
#nginx_keepalived_vip: 192.168.160.3
#nginx_keepalived_virtual_router_id: '55'
#nginx_keepalived_vrrp_instance_interface: eth0

# es
es_root_dir: '/data01/es'
es_cluster_name: 'es-cluster-7.3.2'
es_image: '{{ image_repository }}/public/elasticsearch:7.13.2'
es_java_opts: '-Xms4G -Xmx4G'

# kafka
zookeeper_image: '{{ image_repository }}/public/zookeeper-official:3.7'
kafka_image: '{{ image_repository }}/public/kafka:2.13-2.7.0'
kafka_root_dir: '/data01/kafka'
kafka_heap_opts: '-Xmx4G -Xms4G'

# k8s
k8s_keepalived_vip: 192.168.160.5
k8s_keepalived_virtual_router_id: '55'
k8s_keepalived_vrrp_instance_interface: eth0

# kubernetes
control_plane_endpoint: '{{ k8s_keepalived_vip }}:6443'
google_image_repository: '{{ image_repository }}/google_containers'
pod_network_cidr: '10.244.0.0/16'
kubernetes_version: '1.18.19'
component_manifest_dir: '/data01/kube-manifest'

# elk
elk_manifest_root_dir: '{{ component_manifest_dir }}/elk'

# monitor
monitor_manifest_root_dir: '{{ component_manifest_dir }}/monitor'

# redis
redis_data_dir: '/data01/redis'
redis_image: '{{ image_repository }}/public/redis:6.2.4'
redis_maxmemory: '51539607552'

# component result file
kube_component_file: '{{ component_manifest_dir }}/kube-component.md'

# etcd backup
etcd_backup_root_dir: '/data01/etcd'