# 全局刷新文件句柄 关闭tcp6
- name: change sysconf
  hosts: all
  gather_facts: false
  roles:
    - change-sysconf

- name: add nf_conntrack conf
  gather_facts: false
  hosts: all,!nas
  tasks:
    - name: check nf_conntrack exists
      stat:
        path: /proc/sys/net/netfilter/nf_conntrack_count
      register: nf_conntrack

    - name: remove nf_conntrack sysconf
      lineinfile:
        path: /etc/sysctl.conf
        regexp: "^net.netfilter.nf_conntrack_tcp_timeout_established"
        state: absent

    - name: change nf_conntrack buckets
      file:
        path: /etc/modprobe.d/nf_conntrack.conf
        state: touch
      when: nf_conntrack.stat.exists == true

    - name: change /etc/modprobe.d/nf_conntrack.conf
      lineinfile:
        path: /etc/modprobe.d/nf_conntrack.conf
        line: "options nf_conntrack hashsize=262144"
        regexp: "^options nf_conntrack hashsize="
        state: present
      when: nf_conntrack.stat.exists == true

    - name: change nf_conntrack sysconf
      lineinfile:
        path: /etc/sysctl.conf
        line: "net.netfilter.nf_conntrack_tcp_timeout_established = 172800"
        state: present
      when: nf_conntrack.stat.exists == true

    - name: sysctl /etc/sysctl.conf for nf_conntrack
      shell: sysctl -p /etc/sysctl.conf