# 修改rocketmq  es  kafka配置参数
- name: change sysconf
  hosts:
    - nginx
    - rocketmq-namesrv
    - rocketmq-master
    - rocketmq-slave
    - es
    - kafka
  gather_facts: false
  roles:
    - change-sysconf