---
- name: install jdk
  gather_facts: false
  hosts:
    - rocketmq-namesrv
    - rocketmq-master
    - rocketmq-slave
  roles:
    - change-sysconf
    - install-java
  tasks:
    - name: create rocketmq user
      user:
        name: "{{ mq_user }}"
        password: "{{ mq_user_pass }}"
        state: present

- name: install-rocketmq-namesrv
  gather_facts: false
  hosts: rocketmq-namesrv
  roles:
    - rocketmq-namesrv

- name: install-rocketmq-master
  gather_facts: false
  hosts: rocketmq-master
  roles:
    - rocketmq-master

- name: install rocketmq slave
  gather_facts: false
  hosts: rocketmq-slave
  roles:
    - rocketmq-slave

- name: start rocketmq-console
  gather_facts: false
  hosts: rocketmq-console
  roles:
    - rocketmq-console

#- name: check rocketmq status
#  hosts: rocketmq-master
#  gather_facts: false
#  tasks:
#    - name: check rocketmq status
#      shell: |
#        namesrv='{{ groups["rocketmq-namesrv"] | map("regex_replace", "^(.*)$", "\\1:9876") | join(";") }}'
#        ./mqadmin clusterList -n $namesrv
#      args:
#        chdir: "{{ mq_work_dir }}/bin"
#      register: mqstatus
#      when: groups['rocketmq-master'][0] == ansible_ssh_host
#    - name: show rocketmq status
#      debug:
#        msg: "{{ mqstatus.stdout }}"
#      when: groups['rocketmq-master'][0] == ansible_ssh_host