- name: change sys conf
  hosts:
    - rocketmq-namesrv
    - rocketmq-master
    - rocketmq-slave
  tasks:
    - name: change sys conf
      lineinfile:
        dest: /etc/sysctl.conf
        line: "{{ item }}"
    with_items:
      - "vm.drop_caches = 1"
      - "vm.zone_reclaim_mode = 0"
      - "vm.dirty_background_ratio = 50"
      - "vm.dirty_ratio = 50"
      - "vm.page-cluster = 3"
      - "vm.dirty_writeback_centisecs = 360000"
      - "vm.swappiness = 10"

- name: install jdk
  gather_facts: false
  hosts:
    - rocketmq-namesrv
    - rocketmq-master
    - rocketmq-slave
  roles:
    - change-sysconf
    - install-java
  tasks:
    - name: create rocketmq user
      user:
        name: "{{ rocketmq_user }}"
        password: "{{ rocketmq_user_pass }}"
        state: present

- name: install-rocketmq-namesrv
  gather_facts: false
  hosts: rocketmq-namesrv
  roles:
    - rocketmq-namesrv

- name: install-rocketmq-master
  gather_facts: false
  hosts: rocketmq-master
  roles:
    - rocketmq-master

- name: install rocketmq slave
  gather_facts: false
  hosts: rocketmq-slave
  roles:
    - rocketmq-slave

- name: start rocketmq-console
  gather_facts: false
  hosts: rocketmq-console
  roles:
    - rocketmq-console

- name: create topic
  gather_facts: false
  hosts: rocketmq-namesrv
  tasks:
    - name: set java env conf ~/.bashrc
      lineinfile:
        dest: ~/.bashrc
        state: present
        line: "{{ item }}"
      with_items:
        - "export JAVA_HOME={{ jdk_dir }}"
        - "export JRE_HOME=${JAVA_HOME}/jre"
        - "export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib"
        - "export PATH=${JAVA_HOME}/bin:$PATH"
    - name: create topic
      shell: |
        ./mqadmin updateTopic -n localhost:9876 -b {{ groups["rocketmq-master"][0] }}:10911 -t {{ item }} -p 6 -r 16 -w 16
        ./mqadmin updateTopic -n localhost:9876 -b {{ groups["rocketmq-master"][1] }}:10911 -t {{ item }} -p 6 -r 16 -w 16
      when: groups['rocketmq-namesrv'][0] == ansible_ssh_host
      args:
        chdir: "{{ rocketmq_root_dir }}/bin"
      with_items:
        - "{{ rocket_topic_list }}"

#     查看rocketmq topic，先暂时不做。。直接进页面看
#     - name: show rocketmq topic topic list
#       shell: ./mqadmin topicRoute -t {{ item }} -n localhost:9876
#       when: groups['rocketmq-namesrv'][0] == ansible_ssh_host
#       args:
#         chdir: "{{ rocketmq_root_dir }}/bin"
#       register: result
#       with_items:
#         - "{{ rocket_topic_list }}"
#
#     - name: show result
#       debug:
#          msg: "{{ item }}"
#       with_items:
#         - "{{ result }}"
