---
- hosts: localhost
  tasks:
    - name: ssh key 生成
      openssh_keypair:
        path: ~/.ssh/id_rsa

- hosts: harbor
  tasks:
    - name: ssh-copy
      authorized_key: user=root key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    - name: mkdir harbor
      shell: "mkdir -p {{ harbor_root_dir }}"

- hosts: localhost
  name: copy harbor
  gather_facts: false
  vars:
    harbor_hosts: "{{groups['harbor']|join(',')}}"
  tasks:
   - name: copy harbor
     shell: "scp -r {{ harbor_tar }} {{ item }}:{{ harbor_root_dir }}"
     with_items: '{{ harbor_hosts.split(",") }}'

- name: install harbor vip
  hosts: harbor
  vars:
    keepalived_vip: '{{ harbor_keepalived_vip }}'
    keepalived_virtual_router_id: '{{ harbor_keepalived_virtual_router_id }}'
    keepalived_vrrp_instance_interface:
      - '{{ harbor_keepalived_vrrp_instance_interface }}'
    health_check_local_script: harbor_healthcheck.sh
  gather_facts: false
  roles:
    - install-keepalived

- name: install harbor
  gather_facts: false
  hosts: harbor
  roles:
    - install-harbor

