- name: create nas dir for monitoring
  hosts: nas
  gather_facts: false
  tasks:
    - name: create nas dir
      file:
        path: "{{ monitor_nfs_path }}"
        state: directory

- name: install k8s monitor
  hosts: k8s-master-init
  gather_facts: false
  roles:
    - k8s-install-monitor

- name: install external monitor
  gather_facts: false
  hosts:
    - eap
    - fdc
    - apc
  roles:
    - install-node-exporter
    - install-process-exporter