# k8s master 创建vip
- name: k8s control plane vip
  hosts:
    - k8s-master-init
    - k8s-master-join
  gather_facts: false
  vars:
    keepalived_vip: "{{ k8s_keepalived_vip }}"
    keepalived_virtual_router_id: "{{ k8s_keepalived_virtual_router_id }}"
    keepalived_vip_gateway: '{{ k8s_keepalived_vip_gateway }}'
    keepalived_vrrp_instance_interface:
      - "{{ k8s_keepalived_vrrp_instance_interface }}"
    health_check_local_script: apiserver_healthcheck.sh
  roles:
    - install-keepalived

# 安装kubelet  kubeadm kubectl
- name: install kubelet kubeadm kubectl
  hosts:
    - k8s-master-init
    - k8s-master-join
    - k8s-worker
  gather_facts: false
  roles:
    - install-kubernetes

# master init命令
- name: k8s master init
  hosts: k8s-master-init
  gather_facts: false
  roles:
    - k8s-master-init

# master join命令
- name: k8s master join
  hosts: k8s-master-join
  gather_facts: false
  roles:
    - k8s-master-join

- name: install pod presets
  hosts:
    - k8s-master-init
    - k8s-master-join
  gather_facts: false
  roles:
    - k8s-change-config

# master worker join
- name: k8s worker join
  hosts: k8s-worker
  gather_facts: false
  roles:
    - k8s-worker-join

# 更新K8S证书
- name: k8s cert update
  hosts:
    - k8s-master-init
    - k8s-master-join
  gather_facts: false
  roles:
    - k8s-cert-update

# 备份etcd集群信息
- name: etcd backup
  hosts:
    - k8s-master-init
    - k8s-master-join
  gather_facts: false
  roles:
    - install-etcd-backup-cron

# 给节点打标签
- name: label k8s node
  hosts: k8s-master-init
  gather_facts: false
  roles:
    - k8s-label-node