- name: change sys conf
  gather_facts: false
  hosts:
    - rocketmq-namesrv
    - rocketmq-broker
  tasks:
    - name: change sys conf
      lineinfile:
        dest: /etc/sysctl.conf
        line: "{{ item }}"
      with_items:
        - "vm.drop_caches = 1"
        - "vm.zone_reclaim_mode = 0"
        - "vm.dirty_background_ratio = 50"
        - "vm.dirty_ratio = 50"
        - "vm.page-cluster = 3"
        - "vm.dirty_writeback_centisecs = 360000"
        - "vm.swappiness = 10"

- name: install jdk
  gather_facts: false
  hosts:
    - rocketmq-namesrv
    - rocketmq-broker
  roles:
    - install-java

- name: install rocketmq namesrv
  gather_facts: false
  hosts: rocketmq-namesrv
  roles:
    - rocketmq-namesrv

- name: install rocketmq broker
  gather_facts: false
  hosts: rocketmq-broker
  roles:
    - rocketmq-broker

- name: install rocketmq console
  gather_facts: false
  hosts: rocketmq-console
  roles:
    - install-docker
    - rocketmq-console

- name: create topic
  gather_facts: false
  hosts: rocketmq-namesrv
  tasks:
    - name: set java env conf ~/.bashrc for rocketmq
      lineinfile:
        dest: ~/.bashrc
        state: present
        line: "{{ item }}"
      with_items:
        - "export JAVA_HOME={{ jdk_dir }}"
        - "export JRE_HOME=${JAVA_HOME}/jre"
        - "export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib"
        - "export PATH=${JAVA_HOME}/bin:$PATH"
    - name: create topic
      shell: |
        ./mqadmin updateTopic -n localhost:9876 -c {{ rocket_cluster_name }} -t {{ item }} -p 6 -r 16 -w 16
      when: groups['rocketmq-namesrv'][0] == ansible_ssh_host
      args:
        chdir: "{{ rocketmq_root_dir }}/bin"
      with_items:
        - test
        - spc-calc-service-chartCalc-topic
        - spc-job-check-post-process
        - spc-mes-save-param
        - spc-rpt-excute-calculate
        - spc-rpt-execute-calculate