- hosts: redis
  gather_facts: false
  vars:
    data_dir: /data01/redis
    clearall: "yes"
    redis_image: 192.168.160.47:8888/public/redis:6.2.4
    redis_port: 6379
    maxmemory: 51539607552
  roles:
    - install-redis
  tasks:
    - name: pause
      shell: sleep 5
    - name: redis cluster info
      shell: docker exec -it redis-node01 /bin/sh -c 'redis-cli cluster info' | grep cluster_state
      register: result
      failed_when: ' "cluster_state:ok" not in result.stdout'