- name: k8s master vip
  hosts: k8s-master
  gather_facts: false
  roles:
    - install-keepalived

- name: install kubelet kubeadm kubectl
  hosts: k8s
  gather_facts: false
  roles:
    - install-kubernetes

- name: k8s master init
  hosts: k8s-master-init
  gather_facts: false
  roles:
    - k8s-master-init

- name: k8s master join
  hosts: k8s-master-join
  gather_facts: false
  roles:
    - k8s-master-join

- name: k8s worker join
  hosts: k8s-worker
  gather_facts: false
  roles:
    - k8s-worker-join

- name: k8s cert update
  hosts: k8s-master
  gather_facts: false
  roles:
    - k8s-cert-update