- name: install ravencast
  hosts: '{{ groups | select("match","ravencast-.*") | list }}'
  gather_facts: false
  roles:
    - install-java
    - install-ravencast-server
    - install-ravencast-agent