- name: create nas dir for monitoring
  hosts: nas
  gather_facts: false
  tasks:
    - name: create nas dir
      file:
        path: "{{ monitor_nfs_path }}"
        state: directory

- name: install k8s monitor
  hosts: k8s-master-init
  gather_facts: false
  roles:
    - k8s-install-monitor

#- name: install node exporter
#  gather_facts: false
#  hosts:
#    - es
#    - redis
#    - kafka
#    - ravencast
#    - nas
#    - rocketmq-namesrv
#    - rocketmq-master
#    - rocketmq-slave
#  roles:
#    - install-node-exporter
#
#- name: install process exporter
#  gather_facts: false
#  hosts:
#    - ravencast
#    - nas
#    - rocketmq-namesrv
#    - rocketmq-master
#    - rocketmq-slave
#  roles:
#    - install-process-exporter