- name: delete admin secret cron
  gather_facts: false
  hosts: k8s-master-init
  tasks:
    - name: add delete secret cron job
      cron:
        name: delete k8s namespace admin secret
        job: kubectl get secret -A | grep admin-token | grep -v qtest | awk '{system("kubectl -n " $1 " delete secret " $2) }'
        special_time: "daily"