- name: k8s control plane vip
  hosts: k8s-master
  gather_facts: false
  vars:
    keepalived_vip: "{{ k8s_keepalived_vip }}"
    keepalived_virtual_router_id: "{{ k8s_keepalived_virtual_router_id }}"
    keepalived_vrrp_instance_interface:
      - "{{ k8s_keepalived_vrrp_instance_interface }}"
  roles:
    - install-keepalived

- name: install kubelet kubeadm kubect
  hosts: k8s
  gather_facts: false
  roles:
    - install-kubernetes

- name: k8s master init
  hosts: k8s-master-init
  gather_facts: false
  roles:
    - k8s-master-init

- name: k8s master join
  hosts: k8s-master-join
  gather_facts: false
  roles:
    - k8s-master-join

- name: k8s worker join
  hosts: k8s-worker
  gather_facts: false
  roles:
    - k8s-worker-join

- name: k8s cert update
  hosts: k8s-master
  gather_facts: false
  roles:
    - k8s-cert-update