- name: create nas dir for monitoring
  hosts: nas
  gather_facts: false
  tasks:
    - name: create nas dir
      file:
        path: "{{ monitor_nfs_path }}"
        state: directory
      when: monitor_nfs_path_existed is not defined or monitor_nfs_path_existed == false

- name: install sync
  hosts: localhost
  gather_facts: false
  tasks:
    - name: install rsync
      shell: yum install rsync -y

- name: install k8s monitor
  hosts: k8s-master-init
  gather_facts: false
  roles:
    - k8s-install-monitor