- name: uninstall svn
  hosts: svn
  gather_facts: false
  ignore_errors: true
  ignore_unreachable: true
  vars:
    svn_root_dir: '{{ svn_data_root_dir }}'
    svn_image: '{{ svn_image_url }}'
  roles:
    - uninstall-svn
