- name: uninstall kubernetes worker
  hosts:
    - k8s-worker
  gather_facts: false
  ignore_errors: true
  ignore_unreachable: true
  roles:
    - uninstall-kubernetes
- name: uninstall kubernetes master
  hosts:
    - k8s-master
  gather_facts: false
  ignore_errors: true
  ignore_unreachable: true
  roles:
    - uninstall-kubernetes

- name: remove kubernetes dirs
  shell: |
    rm -rf /etc/kubernetes
    rm -rf /var/lib/kubelet
    rm -rf /var/lib/etcd

