- name: uninstall rocketmq console
  hosts: rocketmq-console
  gather_facts: false
  tasks:
    - name: check docker container running
      stat:
        path: "{{ rocketmq_root_dir }}/docker-compose.yml"
      register: docker_compose_file
    - name: stop rocketmq console
      shell: docker-compose down
      when: docker_compose_file.stat.exists == true
      args:
        chdir: "{{ rocketmq_root_dir }}"

- name: uninstall rocketmq namesrv
  gather_facts: false
  hosts: rocketmq-namesrv
  tasks:
    - name: check docker container running
      stat:
        path: "{{ rocketmq_root_dir }}/bin/rmq-tools.sh"
      register: rocketmq_tools
    - name: remove rocketmq namesrv
      become_user: "{{ rocketmq_user }}"
      when: rocketmq_tools.stat.exists == true
      shell: "{{ rocketmq_root_dir }}/bin/rmq-tools.sh namesrv stop"

- name: uninstall rocketmq slave
  gather_facts: false
  hosts:
    - rocketmq-slave
    - rocketmq-master
  tasks:
    - name: check docker container running
      stat:
        path: "{{ rocketmq_root_dir }}/bin/rmq-tools.sh"
      register: rocketmq_tools
    - name: remove rocketmq slave
      when: rocketmq_tools.stat.exists == true
      become_user: "{{ rocketmq_user }}"
      shell: "{{ rocketmq_root_dir }}/bin/rmq-tools.sh {{ broker_name }} stop"

- name: remove rocketmq env
  gather_facts: false
  hosts:
    - rocketmq-namesrv
    - rocketmq-slave
    - rocketmq-master
    - rocketmq-console
  tasks:
    - name: remove rocketmq env
      lineinfile:
        dest: /etc/profile
        line: "{{ item }}"
        state: absent
      with_items:
        - "export RMQ_BIN={{ rocketmq_root_dir }}/bin"
        - "export PATH=$RMQ_BIN:$PATH"
        - "export ROCKETMQ_HOME={{ rocketmq_root_dir }}"

- name: remove rocketmq user
  gather_facts: false
  hosts:
    - rocketmq-namesrv
    - rocketmq-slave
    - rocketmq-master
  tasks:
    - name: wait for rocketmq process down
      shell: sleep 10
    - name: remove rocketmq user
      user:
        name: "{{ rocketmq_user }}"
        state: absent

- name: remove rocketmq dirs
  gather_facts: false
  hosts:
    - rocketmq-namesrv
    - rocketmq-slave
    - rocketmq-master
    - rocketmq-console
  tasks:
    - name: remove rocketmq dirs
      shell: |
        rm -rf {{ rocketmq_root_dir }}
        rm -rf {{ rocketmq_root_dir }}
