- name: uninstall rocketmq namesrv
  gather_facts: false
  hosts: rocketmq-namesrv
  tasks:
    - name: check docker container running
      stat:
        path: "{{ rocketmq_root_dir }}/bin/rmq-tools.sh"
      register: rocketmq_tools
    - name: remove rocketmq namesrv
      when: rocketmq_tools.stat.exists == true
      shell: "{{ rocketmq_root_dir }}/bin/rmq-tools.sh namesrv stop"

- name: uninstall rocketmq broker
  gather_facts: false
  hosts:
    - rocketmq-broker
  tasks:
    - name: check rmq tools exist
      stat:
        path: "{{ rocketmq_root_dir }}/bin/rmq-tools.sh"
      register: rocketmq_tools
    - name: remove rocketmq broker
      when: rocketmq_tools.stat.exists == true
      shell: "{{ rocketmq_root_dir }}/bin/rmq-tools.sh {{ broker_name }} stop"

- name: remove rocketmq user
  gather_facts: false
  hosts:
    - rocketmq-namesrv
    - rocketmq-broker

- name: remove rocketmq dirs
  gather_facts: false
  hosts:
    - rocketmq-namesrv
    - rocketmq-broker
    - rocketmq-console
  tasks:
    - name: remove rocketmq dirs
      shell: |
        rm -rf {{ rocketmq_root_dir }}
        rm -rf {{ rocketmq_root_dir }}
