- name: uninstall node exporter docker
  hosts: all
  gather_facts: false
  tasks:
    - name: docker-compose stat
      stat:
        path: '{{ node_exporter_root_dir }}/docker-compose.yaml'
      register: docker_compose_file

    - name: stop docker container
      shell: docker-compose down
      args:
        chdir: '{{ node_exporter_root_dir }}'
      when: docker_compose_file.stat.exists == true

    - name: remove dir
      file:
        path: '{{ node_exporter_root_dir }}'
        state: absent