apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rtd.fullname" . }}-workflow
  labels:
    {{- include "rtd.workflow.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.workflow.replicaCount }}
  selector:
    matchLabels:
      {{- include "rtd.workflow.labels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rtd.workflow.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rtd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "rtd.fullname" . }}-workflow
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.workflow.image.repository }}:{{ .Values.workflow.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.workflow.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: test
            - name: SERVER_PORT
              value: '8080'
            - name: DB_IP
              value: {{ .Values.workflow.env.db_ip | quote}}
            - name: DB_PORT
              value: {{ .Values.workflow.env.db_port | quote}}
            - name: DB_USER_NAME
              value: {{ .Values.workflow.env.db_user_name | quote}}
            - name: DB_USER_PWD
              value: {{ .Values.workflow.env.db_user_pwd | quote}}
            - name: DB_USER_NAME_QUARTZ
              value: RTD_QUARZ
            - name: WORKFLOW_ENGINE_ENDPOINT
              value: {{ .Release.Name}}-ruleengine.{{ .Release.Namespace}}:80
            - name: DATASOURCE_AGENT_ENDPOINT
              value: rtd-datasource.rtd:80
            - name: FILE_SERVER_TYPE
              value: NAS
            - name: FILE_PATH
              value: /usr/importFile
            - name: ZK_TIME_OUT
              value: '40000'
            - name: ZK_HOST
              value: "{{ .Release.Name}}-{{ .Values.rtd_common.zk_host_surfix }}.{{ .Release.Namespace}}"
            - name: ZK_PORT
              value: {{ .Values.rtd_common.zk_port | quote}}
            - name: RTD_NODE_PATH
              value: {{ .Values.rtd_common.zk_node | quote}}
            - name: GRPC_ENDPOINT
              value: rtd-ruleengine
            - name: GRPC_ENDPOINT_PORT
              value: '8999'
            - name: ZOOKEEPER_ENABLE
              value: {{ .Values.rtd_common.zk_enable | quote}}
            - name: RAVENCAST_ENABLE
              value: 'true'
            - name: RAVENCAST_HOSTS
              value: {{ .Values.workflow.env.ravencast_hosts | quote}}
            - name: RAVENCAST_SESSION
              value: {{ .Values.workflow.env.ravencast_session | quote}}
            - name: RAVENCAST_CHANNEL
              value: {{ .Values.workflow.env.ravencast_channel | quote}}
        
          livenessProbe:
            httpGet:
              path: /workflow/v1/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 400
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        
          readinessProbe:
            httpGet:
              path: /workflow/v1/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3

          resources:
            {{- toYaml .Values.workflow.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.workflow.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

