apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rtd.fullname" . }}-ruleengine-dc2
  labels:
    zone: dc2
    {{- include "rtd.ruleengine.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ruleengine.replicaCount }}
  selector:
    matchLabels:
      zone: dc2
      {{- include "rtd.ruleengine.labels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        zone: dc2
        {{- include "rtd.ruleengine.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rtd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "rtd.fullname" . }}-ruleengine
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.ruleengine.image.repository }}:{{ .Values.ruleengine.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ruleengine.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8999
              protocol: TCP
          env:
            - name: SERVER_PORT
              value: '8999'
            - name: ZK_ENABLE
              value: {{ .Values.rtd_common.zk_enable | quote}}
            - name: ZK_HOST
              value: "{{ .Release.Name}}-{{ .Values.rtd_common.zk_host_surfix }}.{{ .Release.Namespace}}"
            - name: ZK_PORT
              value: {{ .Values.rtd_common.zk_port | quote}}
            - name: ZK_NODE
              value: {{ .Values.rtd_common.zk_node | quote}}
            - name: FILE_SERVER_TYPE
              value: {{ .Values.rtd_common.file_server_type | quote}}
            - name: IMPORT_FILE_PATH
              value: '/data/ruleengine/resources'
            - name: LOG_FILE_PATH
              value: '/data/ruleengine/logs'
            - name: DATA_FILE_PATH
              value: '/data/ruleengine/data'

          startupProbe:
            exec:
              command:
                - /bin/grpc_health_probe
                - '-addr=localhost:8999'
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 8
          livenessProbe:
            exec:
              command:
                - /bin/grpc_health_probe
                - '-addr=localhost:8999'
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /bin/grpc_health_probe
                - '-addr=localhost:8999'
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command:
                  - sleep
                  - '40'
          resources:
            {{- toYaml .Values.ruleengine.resources | nindent 12 }}

          {{- with .Values.ruleengine.volumeMounts}}
          volumeMounts:
            {{- toYaml . | nindent 12}}
          {{- end }}

      {{- with .Values.ruleengine.volumes}}
      volumes:
        {{- toYaml . | nindent 12}}
      {{- end }}

      nodeSelector:
        zone: dc2
      {{- with .Values.ruleengine.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

