apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rtd.fullname" . }}-workflow-dc1
  labels:
    {{- include "rtd.workflow.labels" . | nindent 4 }}
    zone: dc1
spec:
  replicas: {{ .Values.workflow.replicaCount }}
  selector:
    matchLabels:
      zone: dc1
      {{- include "rtd.workflow.labels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        zone: dc1
        {{- include "rtd.workflow.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rtd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "rtd.fullname" . }}-workflow
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.workflow.image.repository }}:{{ .Values.workflow.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.workflow.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: SERVER_PORT
              value: '8080'
            - name: DB_IP
              value: {{ .Values.workflow.env.db_ip | quote}}
            - name: DB_PORT
              value: {{ .Values.workflow.env.db_port | quote}}
            - name: DB_USER_NAME
              value: {{ .Values.workflow.env.db_user_name | quote}}
            - name: DB_USER_PWD
              value: {{ .Values.workflow.env.db_user_pwd | quote}}
            - name: FILE_SERVER_TYPE
              value: NAS
            - name: IMPORT_FILE_PATH
              value: /usr/importFile
            - name: ZK_TIME_OUT
              value: '40000'
            - name: ZK_HOST
              value: "{{ .Release.Name}}-{{ .Values.rtd_common.zk_host_surfix }}.{{ .Release.Namespace}}"
            - name: ZK_PORT
              value: {{ .Values.rtd_common.zk_port | quote}}
            - name: ZK_NODE
              value: {{ .Values.rtd_common.zk_node | quote}}
            - name: GRPC_ENDPOINT
              value: rtd-ruleengine
            - name: GRPC_ENDPOINT_PORT
              value: '8999'
            - name: ZK_ENABLE
              value: {{ .Values.rtd_common.zk_enable | quote}}
            - name: RAVENCAST_ENABLE
              value: 'true'
            - name: RAVENCAST_HOSTS
              value: {{ .Values.workflow.env.ravencast_hosts | quote}}
            - name: RAVENCAST_SESSION
              value: {{ .Values.workflow.env.ravencast_session | quote}}
            - name: RAVENCAST_CHANNEL
              value: {{ .Values.workflow.env.ravencast_channel | quote}}
        
          startupProbe:
            httpGet:
              path: /workflow/v1/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 8
          livenessProbe:
            httpGet:
              path: /workflow/v1/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
        
          readinessProbe:
            httpGet:
              path: /workflow/v1/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          lifecycle:
            preStop:
              exec:
                command:
                  - sleep
                  - '40'
          resources:
            {{- toYaml .Values.workflow.resources | nindent 12 }}
      nodeSelector:
        zone: dc1
      {{- with .Values.workflow.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

