apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rtd.fullname" . }}-workflow
  labels:
    {{- include "rtd.workflow.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.workflow.replicaCount }}
  selector:
    matchLabels:
      {{- include "rtd.workflow.labels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rtd.workflow.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rtd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "rtd.fullname" . }}-workflow
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.workflow.image.repository }}:{{ .Values.workflow.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.workflow.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP

          {{- with .Values.workflow.env }}
          env:
            {{- toYaml . | nindent 12}}
          {{- end }}

          {{- with .Values.workflow.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12}}
          {{- end }}
          {{- with .Values.workflow.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12}}
          {{- end }}

          resources:
            {{- toYaml .Values.workflow.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.workflow.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

