apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
  generation: 1
  name: {{ include "rtd.fullname" . }}-web
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ .Values.rtd_common.Host}}`)&&PathPrefix(`{{ .Values.web.PathPrefix}}`)
      services:
        - name: {{ include "rtd.fullname" . }}-web
          port: 80
