apiVersion: v1
kind: Service
metadata:
  name: {{ include "rtd.fullname" . }}-web
  labels:
    {{- include "rtd.common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      {{- if and (eq .Values.web.service.type "NodePort") .Values.web.service.nodePort }}
      nodePort: {{ .Values.web.service.nodePort }}
      {{- end }}
      targetPort: {{ .Values.web.service.targetPort }}
      protocol: {{ .Values.web.service.protocol }}
      name: {{ .Values.web.service.name }}
  selector:
    {{- include "rtd.web.labels" . | nindent 4 }}
