apiVersion: v1
kind: Service
metadata:
  name: {{ include "rtd.fullname" . }}-ruleengine
  labels:
    {{- include "rtd.common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ruleengine.service.type }}
  ports:
    - port: {{ .Values.ruleengine.service.port }}
      targetPort: {{ .Values.ruleengine.service.targetPort }}
      protocol: {{ .Values.ruleengine.service.protocol }}
      name: {{ .Values.ruleengine.service.name }}
  selector:
    {{- include "rtd.ruleengine.labels" . | nindent 4 }}
