---
# 修改主机名
- hosts: all
  gather_facts: false
  tasks:
  - name: set hostname
    shell: hostnamectl set-hostname {{ host_name }}
  - name: replace hosts
    template: src=/etc/ansible/hosts.j2 dest=/etc/hosts

# 安装docker
- hosts: all
  gather_facts: false
  roles:
    - docker

#修改 docker daemon.json排除Harbor的兩台服務器
- hosts: all
  gather_facts: false
  vars:
    - insecureregistries: '["192.168.160.47:8888"]'
    - dataroot: '"/data01/docker/"'
  roles:
    - docker-daemon

