filebeat.inputs:
  - type: log
    paths:
      - /var/lib/docker/overlay2/*/diff/opt/RMSServer_linux/Logs/*.log
    multiline.pattern: '^\d{4}-\d{1,2}-\d{1,2}'
    multiline.negate: true
    multiline.match: after
    processors:
      - add_fields:
          target: ''
          fields:
            kubernetes.labels.app: rms-server
            kubernetes.namespace: rms
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    multiline.pattern: '^\d{4}-\d{1,2}-\d{1,2}'
    multiline.negate: true
    multiline.match: after
    processors:
      - add_kubernetes_metadata:
          in_cluster: true
      - drop_fields:
          fields:
            - "agent"
            - "host"
            - "log"
            - "input"
            - "ecs"
            - "container"
          ignore_missing: true
      - drop_event:
          when:
            or:
              - equals:
                  kubernetes.namespace: default
              - equals:
                  kubernetes.namespace: traefik
              - equals:
                  kubernetes.namespace: elk
              - equals:
                  kubernetes.namespace: monitoring
              - equals:
                  kubernetes.namespace: kube-system
              - equals:
                  kubernetes.namespace: kubernetes-dashboard
output.kafka:
  hosts: [ "192.168.161.203:9092", "192.168.161.198:9092", "192.168.161.201:9092" ]
  topic: log
  required_acks: 0
  worker: 8
  keep_alive: 15
monitoring:
  enabled: true
  elasticsearch:
    hosts: [ "192.168.161.200:9200", "192.168.161.196:9200", "192.168.161.193:9200" ]