---
# 修改主机名
- hosts: k8s
  gather_facts: false
  tasks:
  - name: set hostname
    shell: hostnamectl set-hostname {{ host_name }}
  - name: replace hosts
    template: src=/etc/ansible/hosts.j2 dest=/etc/hosts

# 安装docker
- hosts: k8s
  gather_facts: false
  roles:
    - docker

#修改 docker daemon.json排除Harbor的兩台服務器
- hosts: k8s
  gather_facts: false
  vars:
    - insecureregistries: '["192.168.160.47:8888"]'
    - dataroot: '"/data01/docker/"'
  roles:
    - docker-daemon

# k8s vip role改名字叫 keeaplived，加check逻辑，先只启动master那个，跑完了在启动其他的，确保k8s init没有问题
- hosts: k8s-master
  gather_facts: false
  vars:
    vip:
      - 192.168.160.20
    virtual_router_id: '60'
    vrrp_instance_interface: 
      - eth0
  roles:
    - keepalived

- hosts: k8s
  gather_facts: false
  roles:
    - k8s-product-test

- hosts: k8s-master-init
  gather_facts: false
  tasks:
  - name: init k8s
    shell: |
      kubeadm init --control-plane-endpoint="192.168.160.20:6443"  \
      --image-repository="192.168.160.47:8888/google_containers"    \
      --pod-network-cidr="10.244.0.0/16" --kubernetes-version=1.18.19 --upload-certs
    register: result
  - name: show
    debug:
      msg: "{{ result }}"
  - name: add admin.conf
    shell: |
        mkdir -p $HOME/.kube
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config

- hosts: k8s-master-join
  gather_facts: false
  tasks:
  - name: join k8s
    debug: 
      msg: "{{ result }}"
  