---
- hosts: k8s-worker
  gather_facts: false
  tasks:
  - name: worker join cluster
    shell:  |
      kubeadm join 192.168.160.20:6443 --token ph57tx.7nh7jlwyf4thdggg \
      --discovery-token-ca-cert-hash sha256:3c877cbcbd4c30ea68e553e92e0e8e8db30484c0283df049394284fd12a87f1d

- hosts: k8s-master
  gather_facts: false
  tasks:
  - name: master join cluster
    shell:  |
      kubeadm join 192.168.160.20:6443 --token ph57tx.7nh7jlwyf4thdggg \
      --discovery-token-ca-cert-hash sha256:3c877cbcbd4c30ea68e553e92e0e8e8db30484c0283df049394284fd12a87f1d \
      --control-plane --certificate-key 772b79eb08d7562fe018beebd92d0edb14c162d4da7dfd359823b7d9e7d9d656
  - name: mkdir -p $HOME/.kube
    shell: mkdir -p $HOME/.kube
  - name: cp admin.conf
    shell: sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  - name: chown config
    shell: sudo chown $(id -u):$(id -g) $HOME/.kube/config