server:
  port: 9990
  env: pro
  servlet:
    context-path: /monitor-server
spring:
  application:
    name: imonitor-server
  profiles:
    include: alarmdesc
  servlet:
    multipart:
      maxFileSize: 10MB
  redis:
    database: 0
    namespace: monitoring
    cluster:
      max-redirects: 3
      nodes: 192.168.160.110:6379,192.168.160.114:6379,192.168.160.109:6379,192.168.160.112:6379,192.168.160.108:6379,192.168.160.113:6379
    #password:
    lettuce:
      pool:
        max-idle: 5
        max-active: 8
        min-idle: 2
logging:
  file:
    path: ./log

#自定义配置参数
base:
  #通信token，请和server端配置的hpcToken保持一致
  hpcToken: hpcMonitor
  extConfigPath: /monitorgsdata/config

elasticsearch:
  schema: http
  address: 192.168.163.50:9200,192.168.161.200:9200,192.168.161.242:9200
  connectTimeout: 5000
  socketTimeout: 5000
  connectionRequestTimeout: 5000
  maxConnectNum: 100
  maxConnectPerRoute: 100

#告警配置
mail:
  #邮件服务设置
  smtpHost: 192.168.160.1
  smtpPort: 587
  smtpSSL: false
  socketConnectionTimeout: 60000
  socketTimeout: 200000
  #发件人邮箱地址
  fromMailAddress: dbalert@cicem.fa
  #邮件服务器用户名(发件人)
  mailUser: dbalert@cicem.fa
  #邮件服务器登录密码(发件人)
  mailPassword: CEIIsFXKP/ipkkXi+70qbg==
