- name: create dir
  file:
    path: '{{ node_exporter_root_dir }}'
    state: directory

- name: docker-compose stat
  stat:
    path: '{{ node_exporter_root_dir }}/docker-compose.yaml'
  register: docker_compose_file

- name: stop docker container
  become_user: '{{ cim_ops_user }}'
  shell: docker-compose down
  args:
    chdir: '{{ node_exporter_root_dir }}'
  when: docker_compose_file.stat.exists == true

- name: install node-exporter
  template:
    src: docker-compose.yaml.j2
    dest: '{{ node_exporter_root_dir }}/docker-compose.yaml'

- name: chown node export dir
  file:
    path: '{{ node_exporter_root_dir }}'
    owner: '{{ cim_ops_user }}'
    group: docker
    recurse: yes

- name: docker-compose up
  become_user: '{{ cim_ops_user }}'
  shell: docker-compose up -d
  args:
    chdir: '{{ node_exporter_root_dir }}'
