- name: yum -y remove postfix
  shell: yum -y remove postfix

- name: rm postfix image
  shell: docker stop mailserver && docker rm -f mailserver

- name: start postfix
  shell:  |
     docker run -d --net=host -e TZ=Asia/Shanghai -v /data01/mail-data:/data \
     --name "mailserver" -h "{{ ansible_ssh_host }}" --restart=always -t {{ mail_image }}
