- name: create es dir
  file:
    path: "{{ es_root_dir }}"
    state: directory

- name: dispatch docker-compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ es_root_dir }}/docker-compose.yml"

- name: dispatch config file
  template:
    src: elasticsearch.yml.j2
    dest: "{{ es_root_dir }}/elasticsearch.yml"

- name: chmod es data dir
  file:
    path: '{{ es_root_dir }}/data'
    mode: 0776
    state: directory
    recurse: no

- name: docker-compose down
  shell: docker-compose -f {{ es_root_dir }}/docker-compose.yml down

- name: docker-compose up
  shell: docker-compose -f {{ es_root_dir }}/docker-compose.yml up -d

- name: wait es start complete
  wait_for:
    port: 9200
    delay: 5

- name: check es state
  uri:
    url: http://localhost:9200/_cat/health?v
    return_content: yes
  register: this
  failed_when: "'green' not in this.content"

- name: send index template conf
  template:
    src: index-template.json.j2
    dest: '{{ es_root_dir }}/index-template.json'

- name: add index template
  shell: |
    curl -H 'Content-Type: application/json' -XPUT -d @index-template.json http://localhost:9200/_template/app-log
  args:
    chdir: '{{ es_root_dir }}'