- name: create dir
  file:
    path: "{{ es_root_dir }}"
    state: directory

- name: dispatch docker-compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ es_root_dir }}/docker-compose.yml"

- name: dispatch config file
  template:
    src: elasticsearch.yml.j2
    dest: "{{ es_root_dir }}/elasticsearch.yml"

- name: chmod data dir
  shell: "mkdir -p {{ es_root_dir }}/data && chmod 776 -R {{ es_root_dir }}/data"

- name: docker-compose up
  shell: docker-compose -f {{ es_root_dir }}/docker-compose.yml up -d

- name: clear expired index
  cron:
    name: 'clear es expired index'
    minute: 0
    hour: 0
    day: '{{ es_clear_at_day }}'
    job: 'curl -XDELETE http://localhost:9200/*-$(date -d "{{ es_clear_month_ago }} month ago" +%Y-%m)'
- name: check es state
  shell: sleep 30 && curl http://localhost:9200/_cat/health?v
  register: result
  when: ansible_ssh_host == groups['es'][0]

- name: show result
  debug:
    msg: "{{ result.stdout_lines }}"
  when: ansible_ssh_host == groups['es'][0]

- name: pause
  command: sleep 10