- name: create dir
  file:
    path: "{{ es_root_dir }}"
    state: directory

- name: dispatch docker-compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ es_root_dir }}/docker-compose.yml"

- name: dispatch config file
  template:
    src: elasticsearch.yml.j2
    dest: "{{ es_root_dir }}/elasticsearch.yml"

- name: chmod data dir
  shell: "mkdir -p {{ es_root_dir }}/data && chmod 776 -R {{ es_root_dir }}/data"

- name: chown es dir
  file:
    path: {{ es_root_dir }}
    owner: '{{ cim_ops_user }}'
    group: 'docker'
    recurse: yes

- name: docker-compose down
  become_user: '{{ cim_ops_user }}'
  shell: docker-compose -f {{ es_root_dir }}/docker-compose.yml down

- name: docker-compose up
  become_user: '{{ cim_ops_user }}'
  shell: docker-compose -f {{ es_root_dir }}/docker-compose.yml up -d

- name: add clear cron job
  cron:
    name: 'clear es expired index'
    minute: 0
    hour: 0
    day: '{{ es_clear_at_day }}'
    job: 'curl -XDELETE http://localhost:9200/*-$(date -d "{{ es_clear_month_ago }} month ago" +%Y-%m)-*'
    user: '{{ cim_ops_user }}'

- name: check es state
  shell: sleep 30 && curl http://localhost:9200/_cat/health?v
  register: result
  when: ansible_ssh_host == groups['es'][0]

- name: show result
  debug:
    msg: "{{ result.stdout_lines }}"
  when: ansible_ssh_host == groups['es'][0]

- name: send index template conf
  template:
    src: index-template.json.j2
    dest: '{{ es_root_dir }}/index-template.json'
    owner: '{{ cim_ops_user }}'
    group: docker

- name: add index template
  shell: |
    curl -H 'Content-Type: application/json' -XPUT -d @index-template.json http://localhost:9200/_template/app-log
  args:
    chdir: '{{ es_root_dir }}'