- name: install required softwares
  shell: yum install rpcbind nfs-utils -y

- name: start nfs server
  systemd:
    name: rpcbind
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: start nfs server
  systemd:
    name: nfs-server
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: firewalld status
  service:
    name: firewalld
  register: firewalld

- name: config firewalld
  shell: |
    firewall-cmd --permanent --add-service mountd
    firewall-cmd --permanent --add-service rpc-bind
    firewall-cmd --permanent --add-service nfs
    firewall-cmd --reload
  when: firewalld.status.ActiveState == 'active'

- name: eusure nfs root dir exist
  file:
    path: '{{ nfs_root_dir }}'
    state: directory

- name: config nfs permission
  lineinfile:
    path: /etc/exports
    line: "{{ nfs_root_dir }} {{ nfs_client_cidr }}(insecure,rw,sync,no_root_squash,no_all_squash)"
    state: present

- name: re-export nfs dir
  shell: exportfs -r