- name: timedatectl set-timezone Asia/Shanghai
  shell: timedatectl set-timezone Asia/Shanghai

- name: date
  shell: date
  register: date_value

- name: show date
  debug:
    msg: "{{ date_value.stdout }}"

- name: yum install ntp -y
  shell: yum install ntp -y

- name: systemctl enable ntpd
  shell: systemctl enable ntpd

- name: /etc/ntp.conf
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf

- name: /etc/sysconfig/ntpd
  template:
    src: ntpd.j2
    dest: /etc/sysconfig/ntpd

- name: service ntpd start/stop/restart
  shell: service ntpd stop

- name: ntpdate  ntp-server
  shell: ntpdate  {{ ntp_server }}

- name: service ntpd start & enable
  systemd:
    name: ntpd
    state: restarted
    enabled: yes

- name: add auto start ntp when bootstrap
  lineinfile:
    line: "/usr/sbin/ntpdate {{ ntp_server }} && /usr/sbin/hwclock -w"
    regexp: "^/usr/sbin/ntpdate"
    path: /etc/rc.d/rc.local
    state: present
    mode: 0774

- name: remove old ntp conf ntp when bootstrap
  lineinfile:
    line: "/usr/sbin/ntpdate 10.12.117.251 && /usr/sbin/hwclock -w && /usr/sbin/service ntpd start"
    path: /etc/rc.d/rc.local
    state: absent

- name: clear old ntp conf
  lineinfile:
    line: "{{ item }}"
    state: absent
    path: /var/spool/cron/root
  with_items:
    - "#Ansible: ntpdate"
    - "@hourly /usr/sbin/service ntpd stop && /usr/sbin/ntpdate 10.13.253.12 && /usr/sbin/hwclock -w && /usr/sbin/service ntpd start"

- name: overide ntpd systemd service
  template:
    src: ntpd.service.j2
    dest: /usr/lib/systemd/system/ntpd.service

- name: reload ntpd systemd service
  systemd:
    name: ntpd
    daemon_reload: yes
    enabled: yes
    state: restarted