- name: create harbor dir
  shell: mkdir -p {{ harbor_root_dir }}

- name: unarchive harbor
  unarchive: src={{ harbor_tar }} dest={{ harbor_root_dir }}
  when: harbor_archive_already_existed == false
 
- name: copy harbor.yml
  template: src=harbor.yml.j2 dest={{ harbor_root_dir }}/harbor.yml
 
- name: copy install-me.sh
  template: src=install-me.sh.j2 dest={{ harbor_root_dir }}/install-me.sh

- name: chmod +x install-me.sh
  shell: systemctl restart docker

- name: chmod +x install-me.sh
  shell: chmod +x install-me.sh
  args:
   chdir: '{{ harbor_root_dir }}'

- name: install
  shell: "./install-me.sh"
  args:
   chdir: "{{ harbor_root_dir }}"

- name: cp harbor service
  template: src=harbor.service.j2 dest=/usr/lib/systemd/system/harbor.service

- name: enable harbor service
  shell: systemctl enable harbor.service


