- name: check has installed
  stat: path={{ harbor_root_dir }}
  register: p

- name: create harbor dir
  shell: mkdir -p {{ harbor_root_dir }}

- name: unarchive harbor tar
  unarchive:
    src: "{{ harbor_root_dir }}/harbor.tar.gz"
    dest: "{{ harbor_root_dir }}"
    copy: no

- name: remove harbor tar
  shell: rm -rf {{ harbor_root_dir }}/harbor.tar.gz

- name: copy harbor.yml
  template: src=harbor.yml.j2 dest={{ harbor_root_dir }}/harbor.yml
 
- name: copy install-me.sh
  template: src=install-me.sh.j2 dest={{ harbor_root_dir }}/install-me.sh

- name: chmod +x install-me.sh
  shell: systemctl --user {{ cim_ops_user }} restart docker

- name: chmod +x install-me.sh
  shell: chmod +x install-me.sh
  args:
   chdir: '{{ harbor_root_dir }}'

- name: chown harbor dir
  file:
    path: '{{ harbor_root_dir }}'
    owner: '{{ cim_ops_user }}'
    group: docker
    recurse: yes

- name: install
  become_user: '{{ cim_ops_user }}'
  shell: "./install-me.sh"
  args:
   chdir: "{{ harbor_root_dir }}"

- name: cp harbor service
  template:
    src: harbor.service.j2
    dest: /usr/lib/systemd/system/harbor.service
    owner: '{{ cim_ops_user }}'
    group: docker

- name: enable harbor service
  shell: systemctl --user {{ cim_ops_user }} enable harbor.service


