- name: install etcdctl
  copy:
    src: /etc/ansible/tools/etcdctl
    dest: /usr/local/bin
    mode: 0744

- name: install backup shell
  template:
    src: backup_etcd.sh.j2
    dest: "{{ etcd_backup_root_dir }}/backup_etcd.sh"

- name: add etcd backup cron
  cron:
    name: "backup etcd"
    special_time: "hourly"
    job: "{{ etcd_backup_root_dir }}/backup_etcd.sh"