- name: copy agent
  copy:
    src: '{{ package_dir }}/ravencast/Agent'
    dest: "{{ ravencast_agent_dir_path }}"

- name: change mode for plantu-agent
  shell: chmod +x "{{ ravencast_agent_dir_path }}/Agent/plantu-agent"

- name: check ravencast service exists
  stat:
    path: /usr/lib/systemd/system/plantu-agent.service
  register: ravencast_service

- name: install ravencast service
  shell: "{{ ravencast_agent_dir_path }}/Agent/plantu-agent /install"
  when: ravencast_service.stat.exists == false

- name: enable service plantu-agent
  shell: systemctl enable plantu-agent

- name: stop service plantu-agent
  shell: systemctl stop plantu-agent

- name: start service plantu-agent
  shell: systemctl start plantu-agent

- name: overide filebeat conf of ravencast
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml

- name: restart filebeat
  systemd:
    name: filebeat
    state: restarted
    enabled: yes
    daemon_reload: yes