---
apiVersion: v1
kind: Service
metadata:
  name: apc-admin-service
  namespace: pcs
  annotations:
    prometheus.io/http-probe: "true"
    prometheus.io/http-probe-port: "8080"
    prometheus.io/http-probe-path: "/apc-service/api/users/prometheus/health"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/scheme: "http"
    prometheus.io/path: "/apc-service/actuator/prometheus"
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: apc-admin-service
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: apc-admin-service
  namespace: pcs
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/apc-service`) && Host(`pcs-uat.cicem.fa`)
      services:
        - name: apc-admin-service
          port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apc-admin-service-dc1
  namespace: pcs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apc-admin-service
      zone: dc1
  template:
    metadata:
      labels:
        app: apc-admin-service
        zone: dc1
    spec:
      terminationGracePeriodSeconds: 120
      imagePullSecrets:
        - name: harbor
      hostNetwork: false
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 2
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 2
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - apc-admin-service
              weight: 100
      nodeSelector:
        zone: dc1
      initContainers:
        - command:
          - sysctl
          - -w
          - net.ipv4.tcp_keepalive_time=10
          - net.ipv4.tcp_keepalive_probes=2
          - net.ipv4.tcp_keepalive_intvl=5
          image: 10.12.107.150:80/public/busybox:1.34
          imagePullPolicy: IfNotPresent
          name: systemctl
          securityContext:
             privileged: true
      volumes:
        - name: tz-config
          hostPath:
           path: /usr/share/zoneinfo/Asia/Shanghai
      containers:
        - name: apc-admin-service
          image: 10.12.107.150:80/pcs-test/apc-admin-service:1.0.0.2-20220223107140
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod_i"
            - name: SERVER_PORT
              value: "8080"
            - name: DB_HOST
              value: "10.12.117.115"
            - name: DB_PORT
              value: "15400"
            - name: DB_USER
              value: "encrypted.AumCaFwY6UgTYc+RezNwmpypja5PfA+HsAmh5u6qGKBF"
            - name: DB_PWD
              value: "encrypted.AtwKHsrWko2QOKtbos037KNHlDviuYj/KvA+09lsj0o1"
            - name: REDIS_NODES
              value: "10.12.117.151:6379,10.12.117.152:6379,10.12.117.153:6379,10.12.117.154:6379,10.12.117.155:6379,10.12.117.156:6379"            
          ports:
            - containerPort: 8080            
          resources:
            limits:
              cpu: "2"
              memory: 2048Mi
            requests:
              cpu: "0.2"
              memory: 500Mi
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /apc-service/actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 20
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /apc-service/actuator/health/readiness
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /apc-service/actuator/health/liveness
              port: 8080
              scheme: HTTP
            periodSeconds: 6
            successThreshold: 1
            timeoutSeconds: 5
            failureThreshold: 10
          lifecycle:
            preStop:
              exec:
                command: [ "sleep", "40" ]
