---
apiVersion: v1
kind: Service
metadata:
  name: apc-business-service
  namespace: pcs
  annotations:
    prometheus.io/http-probe: "true"
    prometheus.io/http-probe-port: "8080"
    prometheus.io/http-probe-path: "/apc-business-service/api/v1/health"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/scheme: "http"
    prometheus.io/path: "/apc-business-service/api/v1/actuator/prometheus"
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: apc-business-service
---    
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: apc-business-service
  namespace: pcs
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/apc-business-service`) && Host(`pcs-uat.cicem.fa`)
      services:
        - name: apc-business-service
          port: 8080        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apc-business-service-dc1
  namespace: pcs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apc-business-service
      zone: dc1
  template:
    metadata:
      labels:
        app: apc-business-service
        zone: dc1
    spec:
      terminationGracePeriodSeconds: 120
      imagePullSecrets:
        - name: harbor
      hostNetwork: false
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - apc-business-service
              weight: 100
      nodeSelector:
        zone: dc1
      initContainers:
        - command:
          - sysctl
          - -w
          - net.ipv4.tcp_keepalive_time=10
          - net.ipv4.tcp_keepalive_probes=2
          - net.ipv4.tcp_keepalive_intvl=5
          image: 10.12.107.150:80/public/busybox:1.34
          imagePullPolicy: IfNotPresent
          name: systemctl
          securityContext:
            privileged: true
      volumes:
        - name: tz-config
          hostPath:
           path: /usr/share/zoneinfo/Asia/Shanghai
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 2
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 2
      containers:
        - name: apc-business-service
          image: 10.12.107.150:80/pcs-test/apc-business-service:1.0.0.2-20220223106978
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: tz-config
            mountPath: /etc/localtime
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "ilab"
            - name: SERVER_PORT
              value: "8080"
            - name: DB_HOST
              value: "10.12.117.115"
            - name: DB_PORT
              value: "15400"
            - name: DB_USER
              value: "encrypted.AumCaFwY6UgTYc+RezNwmpypja5PfA+HsAmh5u6qGKBF"
            - name: DB_PWD
              value: "encrypted.AtwKHsrWko2QOKtbos037KNHlDviuYj/KvA+09lsj0o1"
            - name: REDIS_NODES
              value: "10.12.117.151:6379,10.12.117.152:6379,10.12.117.153:6379,10.12.117.154:6379,10.12.117.155:6379,10.12.117.156:6379"
            - name: CIPHER1_PATH
              value: "encrypt/cipher1.txt"
            - name: CIPHER2_VALUE
              value: "Z0lHoztyg61L/6ov+uwy0l1rzYzIAt1Sz3o+NMaKGZLGvoL3GT4jtOrmjLXwYLsYPHF155zfGZF/jOqZjVUN1puUtBVFU3k2Hm7Zmn4dn/c4B49kbOuyVqmLbXxKi4k4eemZr3AGkEV+mEb6WlMLXIo5i8kmxnzjLNhl09ZZ1cA="
            - name: WORKER_KEY
              value: "Ar2VzIjw4Ez8vZUAHA3DTZD/NKUt1eR0b80q9XBocmBxyOqR5CpzwXqjRiQN1RIQRZkdedQV6hvG00KxX0T/LKk="
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: 1000Mi
            requests:
              cpu: "0.5"
              memory: 500Mi
          livenessProbe:
            httpGet:
              path: /apc-business-service/api/v1/actuator/health/liveness
              port: 8080
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 30
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /apc-business-service/api/v1/actuator/health/readiness
              port: 8080
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 30
            failureThreshold: 10
          startupProbe:
            httpGet:
              port: 8080
              path: /apc-business-service/api/v1/actuator/health/liveness
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: [ "sleep", "40" ]
