---
kind: Service
apiVersion: v1
metadata:
  name: apc-algorithm-service
  namespace: pcs

spec:
  ports:
    - protocol: TCP
      port: 11005
      targetPort: 11005
  selector:
    app: apc-algorithm-service
  type: ClusterIP
  sessionAffinity: None
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: apc-algorithm-service-dc1
  namespace: pcs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apc-algorithm-service
      zone: dc1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apc-algorithm-service
        zone: dc1
    spec:
      volumes:
        - name: tz-config
          hostPath:
           path: /usr/share/zoneinfo/Asia/Shanghai
      containers:
        - name: apc-algorithm-service
          image: 10.12.107.150:80/pcs-test/apc-algorithm-service:1.0.0-2021121100000
          env:
            - name: QIANDAO_AI_PROFILE
              value: product
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "0.2"
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: tz-config
            mountPath: /etc/localtime
      restartPolicy: Always
      terminationGracePeriodSeconds: 120
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: harbor
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - apc-algorithm-service
                topologyKey: kubernetes.io/hostname
      nodeSelector:
        zone: dc1
      tolerations:
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 2
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 2