apiVersion: v1
kind: Namespace
metadata:
  name: plantu
---
apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: change-timezone
  namespace: plantu
spec:
  selector:
    matchLabels:
  env:
    - name: TZ
      value: "Asia/Shanghai"
  volumeMounts:
    - name: timezone
      mountPath: /etc/localtime
  volumes:
    - name: timezone
      hostPath:
        path: /etc/localtime
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: plantu-admin
  namespace: plantu
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: plantu-admin-rolebinding
  namespace: plantu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: plantu-admin
    namespace: plantu
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: plantu-admin-view-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view-namespaces
subjects:
  - kind: ServiceAccount
    name: plantu-admin
    namespace: plantu
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: plantu-admin-view-crd-resources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view-crd-resources
subjects:
  - kind: ServiceAccount
    name: plantu-admin
    namespace: plantu
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: crd-object-admin
  namespace: plantu
rules:
  - verbs:
      - create
      - delete
      - update
      - list
      - get
      - watch
    apiGroups:
      - '*'
    resources:
      - ingressroutes
      - ingressroutetcps
      - ingressrouteudps
      - middlewares
      - servicemonitors
      - alertmanagers
      - prometheusrules
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: plantu-crd-object-admin
  namespace: plantu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: crd-object-admin
subjects:
  - kind: ServiceAccount
    name: plantu-admin
    namespace: plantu

---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxMC4xMi4xMDcuMTUwOjgwIjp7InVzZXJuYW1lIjoiazhzcHVsbGFjY291bnQiLCJwYXNzd29yZCI6Ims4c3B1bGxhY2NvdW50QWRtaW4iLCJhdXRoIjoiYXpoemNIVnNiR0ZqWTI5MWJuUTZhemh6Y0hWc2JHRmpZMjkxYm5SQlpHMXBiZz09In19fQ==
kind: Secret
metadata:
  name: harbor
  namespace: spc
type: kubernetes.io/dockerconfigjson
# {"auths":{"10.12.107.150:80":{"username":"k8spullaccount","password":"k8spullaccountAdmin","auth":"azhzcHVsbGFjY291bnQ6azhzcHVsbGFjY291bnRBZG1pbg=="}}}