- name: create root dir
  command: mkdir -p {{ mq_data_root_dir }}

- name: send docker-compose.yml
  template: src=docker-compose.yml.j2 dest={{ mq_data_root_dir }}/docker-compose.yml

- name: start up rocketmq-console
  command: docker-compose -f {{ mq_data_root_dir }}/docker-compose.yml up -d