- name: set https proxy
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    state: present
    regexp: '^NETMASK'
    line: NETMASK=255.255.255.128

- name: set /etc/sysconfig/network
  lineinfile:
    path: /etc/sysconfig/network
    state: present
    regexp: '^GATEWAY'
    line: GATEWAY=192.168.160.126

#- name: restart
#  shell: service restart network
