- name: static netmask
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    state: present
    regexp: '^NETMASK'
    line: NETMASK={{ netmask }}

- name: static bootproto
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    state: present
    regexp: '^BOOTPROTO'
    line: BOOTPROTO=static

- name: static gateway
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    state: present
    regexp: '^GATEWAY'
    line: GATEWAY={{ gateway }}

- name: static ip addr
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    state: present
    regexp: '^IPADDR'
    line: IPADDR={{ ansible_ssh_host }}

- name: restart network
  shell: systemctl restart network
