kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: guest
rules:
  - verbs:
      - list
    apiGroups:
      - ''
    resources:
      - secrets
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - pods/attach
      - pods/exec
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - '*'
    resources:
      - storageclasses
      - events
      - jobs
      - ingresses
      - pods
      - pods/attach
      - pods/exec
      - pods/log
      - pods/portforward
      - pods/proxy
      - services/proxy
      - configmaps
      - endpoints
      - persistentvolumeclaims
      - replicationcontrollers
      - replicationcontrollers/scale
      - serviceaccounts
      - services
      - services/status
      - daemonsets
      - deployments
      - deployments/rollback
      - deployments/scale
      - replicasets
      - replicasets/scale
      - statefulsets
      - statefulsets/scale
      - horizontalpodautoscalers
      - namespaces
      - nodes
      - cronjobs
      - roles
      - rolebindings
      - persistentvolumes
      - networkpolicies
      - clusterroles
      - clusterrolebindings
      - customresourcedefinitions
      - ingressroutes
      - ingressroutetcps
      - ingressrouteudps
      - prometheusrules
      - prometheusrules
