apiVersion: v1
kind: ServiceAccount
metadata:
  name: guest
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-resource-guest
subjects:
  - kind: ServiceAccount
    name: guest
    namespace: kube-system
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: namespace-resource-guest
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-resource-guest
subjects:
  - kind: ServiceAccount
    name: guest
    namespace: kube-system
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: cluster-resource-guest