apiVersion: v1
kind: ServiceAccount
metadata:
  name: guest
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: guest-rolebinding
  namespace: kubernetes-dashboard
subjects:
  - kind: ServiceAccount
    name: guest
    namespace: kube-system
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: guest