kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-resource-guest
rules:
  - verbs:
      - list
    apiGroups:
      - '*'
    resources:
      - secrets
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - '*'
    resources:
      - bindings
      - configmaps
      - endpoints
      - events
      - limitranges
      - persistentvolumeclaims
      - pods
      - podtemplates
      - replicationcontrollers
      - resourcequotas
      - serviceaccounts
      - services
      - controllerrevisions
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
      - localsubjectaccessreviews
      - horizontalpodautoscalers
      - cronjobs
      - jobs
      - leases
      - networkpolicies
      - networksets
      - endpointslices
      - events
      - ingresses
      - pods
      - alertmanagers
      - podmonitors
      - probes
      - prometheuses
      - prometheusrules
      - servicemonitors
      - thanosrulers
      - ingresses
      - networkpolicies
      - poddisruptionbudgets
      - rolebindings
      - roles
      - podpresets
      - ingressroutes
      - ingressroutetcps
      - ingressrouteudps
      - middlewares
      - serverstransports
      - tlsoptions
      - tlsstores
      - traefikservices
      - pods/attach
      - pods/exec
      - pods/log
      - pods/portforward
      - pods/proxy
      - services/proxy
      - replicationcontrollers/scale
      - services/status
      - deployments/rollback
      - deployments/scale
      - replicasets/scale
      - statefulsets/scale
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-resource-guest
rules:
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - '*'
    resources:
      - componentstatuses
      - namespaces
      - nodes
      - persistentvolumes
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
      - customresourcedefinitions
      - apiservices
      - tokenreviews
      - selfsubjectaccessreviews
      - selfsubjectrulesreviews
      - subjectaccessreviews
      - certificatesigningrequests
      - bgpconfigurations
      - bgppeers
      - blockaffinities
      - clusterinformations
      - felixconfigurations
      - globalnetworkpolicies
      - globalnetworksets
      - hostendpoints
      - ipamblocks
      - ipamconfigs
      - ipamhandles
      - ippools
      - kubecontrollersconfigurations
      - nodes
      - ingressclasses
      - runtimeclasses
      - podsecuritypolicies
      - clusterrolebindings
      - clusterroles
      - priorityclasses
      - csidrivers
      - csinodes
      - storageclasses
      - volumeattachments
