# Example of a secret config
apiVersion: v1
kind: Secret
metadata:
  name: elastalert-config-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  elastalert_config: |-
    rules_folder: /opt/elastalert/rules
    scan_subdirectories: false
    run_every:
      minutes: 1
    buffer_time:
      minutes: 15
    es_host: elasticsearch.elk
    es_port: 9200
    writeback_index: elastalert
    use_ssl: False
    verify_certs: True
    alert_time_limit:
      minutes: 2880