- name: create root dir
  file:
    path: '{{ process_exporter_root_dir }}'
    state: directory

- name: create config dir
  file:
    path: '{{ process_exporter_root_dir }}/config'
    state: directory

- name: docker-compose stat
  stat:
    path: '{{ process_exporter_root_dir }}/docker-compose.yaml'
  register: docker_compose_file

- name: stop docker container
  shell: docker-compose down
  args:
    chdir: '{{ process_exporter_root_dir }}'
  when: docker_compose_file.stat.exists == true

- name: install node-exporter
  template:
    src: docker-compose.yaml.j2
    dest: '{{ process_exporter_root_dir }}/docker-compose.yaml'

- name: send config file
  copy:
    src: config.yaml
    dest: '{{ process_exporter_root_dir }}/config/config.yaml'

- name: docker-compose up
  shell: docker-compose up -d
  args:
    chdir: '{{ process_exporter_root_dir }}'

- name: wait process exporter ready
  wait_for:
    port: 9256
    delay: 3
    timeout: 30
    msg: 'Timeout waiting for process-exporter respond'
