- name: create root dir
  file:
    path: '{{ process_exporter_root_dir }}'
    state: directory

- name: create config dir
  file:
    path: '{{ process_exporter_root_dir }}/config'
    state: directory

- name: docker-compose stat
  stat:
    path: '{{ process_exporter_root_dir }}/docker-compose.yaml'
  register: docker_compose_file

- name: stop docker container
  become_user: '{{ cim_ops_user }}'
  shell: docker-compose down
  args:
    chdir: '{{ process_exporter_root_dir }}'
  when: docker_compose_file.stat.exists == true

- name: install node-exporter
  template:
    src: docker-compose.yaml.j2
    dest: '{{ process_exporter_root_dir }}/docker-compose.yaml'

- name: send config file
  copy:
    src: config.yaml
    dest: '{{ process_exporter_root_dir }}/config/config.yaml'

- name: chown process exporter dir
  file:
    path: '{{ process_exporter_root_dir }}'
    owner: '{{ cim_ops_user }}'
    group: docker
    recurse: yes

- name: docker-compose up
  become_user: '{{ cim_ops_user }}'
  shell: docker-compose up -d
  args:
    chdir: '{{ process_exporter_root_dir }}'
