process_names:
  - comm:
      - chromium-browse
      - bash
      - prometheus
      - gvim
  - exe:
      - /sbin/upstart
    cmdline:
      - --user
    name: upstart:-user

  - name: "{{.Comm}}"
      cmdline:
        - '.+'