version: '3'
services:
  kafka:
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_HEAP_OPTS: "-Xmx16G -Xms16G"
      # KAFKA_BROKER_ID: 1
      KAFKA_NUM_PARTITIONS: 5
      KAFKA_NUM_NETWORK_THREADS: 9
      KAFKA_NUM_IO_THREADS: 16
      KAFKA_LOG_RETENTION_BYTES: 10737418240
      KAFKA_ADVERTISED_HOST_NAME: 10.28.114.39
      KAFKA_ZOOKEEPER_CONNECT: 10.28.114.39:2181,7.185.18.132:2181,7.185.18.25:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka-data:/kafka