---
apiVersion: v1
kind: Service
metadata:
  name: spc-mspc-service
  namespace: spc
  # annotations:
  #   # 使用http检测应用可用性，手动提供支持http检测的端口
  #   prometheus.io/http-probe: "true"
  #   prometheus.io/http-probe-port: "8080"
  #   prometheus.io/http-probe-path: "/spc-mspc-service/health/healthz"

  #   # 抓取应用的监控指标,路径不填写则为：/metrics
  #   prometheus.io/scrape: "true"
  #   prometheus.io/port: '8080'
  #   prometheus.io/scheme: "http"
  #   prometheus.io/path: '/spc-mspc-service/actuator/prometheus'
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: spc-mspc-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spc-mspc-service-dc1
  namespace: spc
  labels:
    app: spc-mspc-service
    zone: dc1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spc-mspc-service
      zone: dc1
  template:
    metadata:
      labels:
        app: spc-mspc-service
        zone: dc1
    spec:
      imagePullSecrets:
        - name: harbor
      hostNetwork: false
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 2
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 2
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - spc-mspc-service
              weight: 100
      nodeSelector:
        zone: dc1
      initContainers:
        - command:
          - sysctl
          - -w
          - net.ipv4.tcp_keepalive_time=10
          - net.ipv4.tcp_keepalive_probes=2
          - net.ipv4.tcp_keepalive_intvl=5
          image: 10.12.107.150:80/public/busybox:1.34
          imagePullPolicy: Always
          name: setsysctl
          securityContext:
            privileged: true
      containers:
        - name: spc-mspc-service
          image: 10.12.107.150:80/spc-sit/spc-mspc-service:1.0.0
          imagePullPolicy: Always
          env:
            - name: DB_ADDR
              value: '10.12.109.66:15400'
            - name: MSPC_SCHEMA
              value: 'SPCAI'
            - name: MSPC_USER_INFO
              value: 'SPCAI:Spcuser@123'
            - name: SPC_SCHEMA
              value: 'SPCUSER'
            - name: SPC_USER_INFO
              value: 'SPCUSER:Spcuser@123'
            - name: ROCKET_MQ_ADDR
              value: '10.12.117.141:9876;10.12.117.142:9876 '
            - name: ROCKET_MQ_TOPIC
              value: 'spc-mes-save-param'
            - name: ROCKET_MQ_GROUP_ID
              value: 'qiandao_ai'
            - name: REDIS_ADDR
              value: '10.12.117.151:6379,10.12.117.152:6379,10.12.117.153:6379,10.12.117.154:6379,10.12.117.155:6379,10.12.117.156:6379'
            - name: DJANGO_SETTINGS_MODULE
              value: 'qiandao_ai.settings.develop'
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "0.2"
              memory: 200Mi
          # 存活性探针 和 准备就绪探针
          # livenessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /spc-mspc-service/health/
          #     port: 8080
          #     scheme: HTTP
          #   initialDelaySeconds: 120
          #   periodSeconds: 10
          #   successThreshold: 1
          #   timeoutSeconds: 20
          # readinessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /spc-mspc-service/health/
          #     port: 8080
          #     scheme: HTTP
          #   periodSeconds: 10
          #   successThreshold: 1
          #   timeoutSeconds: 10
          # 0宕机(zero-downtime)更新
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sh", "-c", "sleep 30" ]
