- name: rm rpm
  shell: rm -rf /tmp/rpm

- name: copy rpm
  copy:
    src: /etc/ansible/package/k8s-1.18.19
    dest: /tmp/
- name: install rpm
  shell: yum -y localinstall /tmp/k8s-1.18.19/*

- name: ipforward=1
  template:
    src: 99-kubernetes-cri.conf.j2
    dest: /etc/sysctl.d/99-kubernetes-cri.conf

- name: install rpm
  shell: sysctl --system

- name: enable kubelet 
  shell: systemctl enable --now kubelet

- name: restart kubelet 
  shell: systemctl restart kubelet

- name: copy master join
  copy: src=/etc/ansible/k8s_join_shell/{{ groups['k8s-master-init'][0] }}/k8s_master_join.sh dest=k8s_master_join.sh
- name: master join shell
  shell: sh k8s_master_join.sh
- name: add admin.conf
  shell: |
    mkdir -p $HOME/.kube
    cat /etc/kubernetes/admin.conf > $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config


