apiVersion: v1
kind: Endpoints
metadata:
  name: test-prometheus-metics
  namespace: monitoring
subsets:
  - addresses:
      - ip: 127.0.0.1
    ports:
      - port: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: test-prometheus-metics
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: '9200'
spec:
  ports:
    - port: 9200
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: test-prometheus-probe
  namespace: monitoring
subsets:
  - addresses:
      - ip: 127.0.0.1
    ports:
      - port: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: test-prometheus-probe
  namespace: monitoring
  annotations:
    prometheus.io/http-probe: "true"
    prometheus.io/http-probe-port: "9090"
    prometheus.io/http-probe-path: "/"
    prometheus.io/tcp-probe: "true"
spec:
  ports:
    - port: 9090
      targetPort: 9090
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: test-prometheus-tcp-probe
  namespace: monitoring
subsets:
  - addresses:
      - ip: 127.0.0.1
    ports:
      - port: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: test-prometheus-tcp-probe
  namespace: monitoring
  annotations:
    prometheus.io/tcp-probe: "true"
spec:
  ports:
    - port: 9090
      targetPort: 9090
  type: ClusterIP