apiVersion: v1
kind: Namespace
metadata:
  name: spc
---
apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: change-timezone
  namespace: spc
spec:
  selector:
    matchLabels:
  env:
    - name: TZ
      value: "Asia/Shanghai"
  volumeMounts:
    - name: timezone
      mountPath: /etc/localtime
  volumes:
    - name: timezone
      hostPath:
        path: /usr/share/zoneinfo/Asia/Shanghai
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spc-admin
  namespace: spc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spc-admin-rolebinding
  namespace: spc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: spc-admin
    namespace: spc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spc-admin-view-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view-namespaces
subjects:
  - kind: ServiceAccount
    name: spc-admin
    namespace: spc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spc-admin-view-crd-resources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view-crd-resources
subjects:
  - kind: ServiceAccount
    name: spc-admin
    namespace: spc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: crd-object-admin
  namespace: spc
rules:
  - verbs:
      - create
      - delete
      - update
      - list
      - get
      - watch
    apiGroups:
      - '*'
    resources:
      - ingressroutes
      - ingressroutetcps
      - ingressrouteudps
      - middlewares
      - servicemonitors
      - alertmanagers
      - prometheusrules
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spc-crd-object-admin
  namespace: spc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: crd-object-admin
subjects:
  - kind: ServiceAccount
    name: spc-admin
    namespace: spc