---
apiVersion: v1
kind: Service
metadata:
  name: spc-mspc-service
  namespace: spc
  # annotations:
  #   # 使用http检测应用可用性，手动提供支持http检测的端口
  #   prometheus.io/http-probe: "true"
  #   prometheus.io/http-probe-port: "8080"
  #   prometheus.io/http-probe-path: "/spc-mspc-service/health/healthz"

  #   # 抓取应用的监控指标,路径不填写则为：/metrics
  #   prometheus.io/scrape: "true"
  #   prometheus.io/port: '8080'
  #   prometheus.io/scheme: "http"
  #   prometheus.io/path: '/spc-mspc-service/actuator/prometheus'
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: spc-mspc-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spc-mspc-service
  namespace: spc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spc-mspc-service
  template:
    metadata:
      labels:
        app: spc-mspc-service
    spec:
      hostNetwork: false
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 2
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 2
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - spc-mspc-service
              weight: 100
      containers:
        - name: spc-mspc-service
          image: 192.168.160.47:8888/spc-sit/spc-mspc-service:2.0.0-exercise
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_ADDR
              value: '192.168.163.247:15400'
            - name: MSPC_SCHEMA
              value: 'SPCAI'
            - name: MSPC_USER_INFO
              value: 'SPCAI:Spcuser@123'
            - name: SPC_SCHEMA
              value: 'SPCUSER'
            - name: SPC_USER_INFO
              value: 'SPCUSER:Spcuser@123'
            - name: ROCKET_MQ_ADDR
              value: '192.168.163.174:9876;192.168.163.189:9876'
            - name: ROCKET_MQ_TOPIC
              value: 'spc-mes-save-param'
            - name: ROCKET_MQ_GROUP_ID
              value: 'qiandao_ai'
            - name: REDIS_ADDR
              value: '192.168.163.142:6379,192.168.163.202:6379,192.168.163.140:6379,192.168.163.164:6379,192.168.163.174:6379,192.168.163.189:6379'
            - name: DJANGO_SETTINGS_MODULE
              value: 'qiandao_ai.settings.develop'
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "0.2"
              memory: 200Mi
          # 存活性探针 和 准备就绪探针
          # livenessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /spc-mspc-service/health/
          #     port: 8080
          #     scheme: HTTP
          #   initialDelaySeconds: 120
          #   periodSeconds: 10
          #   successThreshold: 1
          #   timeoutSeconds: 20
          # readinessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /spc-mspc-service/health/
          #     port: 8080
          #     scheme: HTTP
          #   periodSeconds: 10
          #   successThreshold: 1
          #   timeoutSeconds: 10
          # 0宕机(zero-downtime)更新
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sh", "-c", "sleep 30" ]
