create tablespace MESVIEW datafile '/data01/gaussdb/data/MESVIEW.dbf' SIZE 50G AUTOEXTEND ON NEXT 50M MAXSIZE 200G extent autoallocate;

CREATE USER "MESVIEW" IDENTIFIED BY 'Spcuser@123' DEFAULT TABLESPACE "MESVIEW";

GRANT CREATE VIEW TO "MESVIEW";
GRANT SELECT ANY DICTIONARY TO "MESVIEW";
GRANT SELECT ANY TABLE TO "MESVIEW";
GRANT CONNECT TO "MESVIEW";
