apiVersion: apps/v1
kind: Deployment
metadata:
  name: apc-design-web-dc2
  namespace: pcs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apc-design-web
      zone: dc2
  template:
    metadata:
      labels:
        app: apc-design-web
        zone: dc2
    spec:
      imagePullSecrets:
        - name: harbor
      hostNetwork: false
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 2
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 2
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - apc-design-web
              weight: 100
      nodeSelector:
        zone: dc2
      volumes:
        - name: tz-config
          hostPath:
           path: /usr/share/zoneinfo/Asia/Shanghai
      containers:
        - name: apc-design-web
          image: 10.12.107.150:80/pcs-test/apc-design-web:1.0.0-2021120978448
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: tz-config
            mountPath: /etc/localtime
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "2"
              memory: 2048Mi
            requests:
              cpu: "0.05"
              memory: 100Mi
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 300
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 3