apiVersion: apps/v1
kind: Deployment
metadata:
  name: apc-connector-service-dc2
  namespace: pcs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apc-connector-service
      zone: dc2
  template:
    metadata:
      labels:
        app: apc-connector-service
        zone: dc2
    spec:
      terminationGracePeriodSeconds: 120
      imagePullSecrets:
        - name: harbor
      hostNetwork: false
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 2
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 2
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - apc-connector-service
              weight: 100
      nodeSelector:
        zone: dc2
      initContainers:
        - command:
          - sysctl
          - -w
          - net.ipv4.tcp_keepalive_time=10
          - net.ipv4.tcp_keepalive_probes=2
          - net.ipv4.tcp_keepalive_intvl=5
          image: 10.12.107.150:80/public/busybox:1.34
          imagePullPolicy: IfNotPresent
          name: systemctl
          securityContext:
             privileged: true
      volumes:
        - name: tz-config
          hostPath:
           path: /usr/share/zoneinfo/Asia/Shanghai
      containers:
        - name: apc-connector-service
          image: 10.12.107.150:80/pcs-test/apc-connector-service:1.0.0.2-20220223107158
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: tz-config
            mountPath: /etc/localtime
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod_i"
            - name: SERVER_PORT
              value: "8080"
            - name: SESSIONID
              value: "pcs_session"
            - name: ADDRESS
              value: "10.12.117.170:10101;10.12.117.171:10101?fallbackToPrimary=true&pingTimeout=20000"
            - name: CHANNEL
              value: "/PTEST/UAT/PCS"
            - name: WORKFLOW_URL
              value: "http://pcs-uat.cicem.fa/workflow-portal/apc/wf-proc-def/"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "2"
              memory: 2048Mi
            requests:
              cpu: "0.2"
              memory: 1024Mi
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /apc-connector-service/actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 20
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /apc-connector-service/actuator/health/readiness
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10         
          startupProbe:
            httpGet:
              port: 8080
              path: /apc-connector-service/actuator/health/liveness
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: [ "sleep", "40" ]
