apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-portal-service-dc2
  namespace: pcs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow-portal-service
      zone: dc2
  template:
    metadata:
      labels:
        app: workflow-portal-service
        zone: dc2
    spec:
      volumes:
        - name: data
          emptyDir: {}
        - name: logdata
          emptyDir: {}
        - name: config
          configMap:
            name: filebeat-portal-config
            defaultMode: 0744
        - name: tz-config
          hostPath:
           path: /usr/share/zoneinfo/Asia/Shanghai
      terminationGracePeriodSeconds: 120
      imagePullSecrets:
        - name: harbor
      hostNetwork: false
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - workflow-portal-service
              weight: 100
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 2
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 2
      nodeSelector:
        zone: dc2
      initContainers:
        - command:
          - sysctl
          - -w
          - net.ipv4.tcp_keepalive_time=10
          - net.ipv4.tcp_keepalive_probes=2
          - net.ipv4.tcp_keepalive_intvl=5
          image: 10.12.107.150:80/public/busybox:1.34
          imagePullPolicy: IfNotPresent
          name: systemctl
          securityContext:
             privileged: true
      containers:
        - name: workflow-portal-service
          image: 10.12.107.150:80/pcs-test/workflow-portal-service:1.0.0.2-20220223106992
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: tz-config
            mountPath: /etc/localtime
          - name: logdata
            mountPath: /data
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod_i"
            - name: SERVER_PORT
              value: "8080"
            - name: DB_HOST
              value: "10.12.117.115"
            - name: DB_PORT
              value: "15400"
            - name: DB_USER
              value: "encrypted.AumCaFwY6UgTYc+RezNwmpypja5PfA+HsAmh5u6qGKBF"
            - name: DB_PWD
              value: "encrypted.AtwKHsrWko2QOKtbos037KNHlDviuYj/KvA+09lsj0o1"
            - name: REDIS_NODES
              value: "10.12.117.151:6379,10.12.117.152:6379,10.12.117.153:6379,10.12.117.154:6379,10.12.117.155:6379,10.12.117.156:6379"
            - name: ES_HOSTS
              value: "10.12.117.121:9200,10.12.117.122:9200,10.12.117.123:9200"
            - name: ROCKETMQ_NODES
              value: "10.12.117.141:9876;10.12.117.142:9876"
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+UseG1GC -XX:MaxRAMPercentage=75.0"
            - name: IS_ENCODE
              value: 'false'
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "2"
              memory: 2048Mi
            requests:
              cpu: "0.2"
              memory: 500Mi
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /workflow-portal/apc/wf-proc-def/health/check
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 20
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /workflow-portal/apc/wf-proc-def/health/check
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              port: 8080
              path: /workflow-portal/apc/wf-proc-def/health/check
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: [ "sleep", "40" ]

        - name: filebeat
          image: '10.12.107.150:80/public/elastic/filebeat:7.13.2'
          args:
            - '-c'
            - /opt/filebeat/filebeat.yml
            - '-e'
          resources:
            limits:
              cpu: "1"
              memory: 200Mi
            requests:
              cpu: "0.1"
              memory: 100Mi
          volumeMounts:
            - name: config
              mountPath: /opt/filebeat/filebeat.yml
              subPath: filebeat.yml
            - name: logdata
              mountPath: /data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sleep", "50" ]
