- name: esure node exporter dir exists
  file:
    path: '{{ node_exporter_root_dir }}'
    state: directory

- name: copy node exporter host package
  synchronize:
    src: '{{ package_dir }}/node_exporter-1.2.2.linux-amd64.tar'
    dest: '{{ node_exporter_root_dir }}/'

- name: copy node exporter unit service
  synchronize:
    src: node-exporter.service
    dest: /usr/lib/systemd/system/