---
- name: modify sysctl
  lineinfile:
    dest: /etc/sysctl.conf
    line: "{{ item }}"
  with_items:
    - "fs.file-max = 1048576"
    - "net.core.somaxconn = 65535"
    - "vm.max_map_count = 655360"
    - "net.ipv6.conf.all.disable_ipv6 = 1"
    - "net.ipv6.conf.default.disable_ipv6 = 1"
    - "net.ipv6.conf.lo.disable_ipv6 = 1"
    - "net.ipv4.tcp_mem = 786432 2097152 3145728"
    - "net.ipv4.tcp_rmem = 4096 4096 16777216"
    - "net.ipv4.tcp_wmem = 4096 4096 16777216"

- name: sysctl enable
  shell: sysctl -p /etc/sysctl.conf

- name: refresh iptables
  shell: iptables -F