- name: modify limits
  lineinfile:
    dest: /etc/security/limits.conf
    line: "{{ item }}"
  with_items:
    - "* - nproc 65535"
    - "* - nofile 1048576"

- name: modify sysctl
  lineinfile:
    dest: /etc/sysctl.conf
    line: "{{ item }}"
  with_items:
    - "fs.file-max = 1048576"
    - "net.core.somaxconn = 65535"
    - "net.ipv4.tcp_max_syn_backlog = 2048"
    - "vm.max_map_count = 655360"
    - "vm.swappiness = 1"
    - "net.ipv6.conf.all.disable_ipv6 = 1"
    - "net.ipv6.conf.default.disable_ipv6 = 1"
    - "net.ipv6.conf.lo.disable_ipv6 = 1"
    - "net.ipv4.tcp_mem = 786432 2097152 3145728"
    - "net.ipv4.tcp_rmem = 4096 4096 16777216"
    - "net.ipv4.tcp_wmem = 4096 4096 16777216"
    - "vm.min_free_kbytes = 61440"

- name: sysctl enable
  shell: sysctl -p /etc/sysctl.conf

- name: check nf_conntrack exists
  stat:
    path: /proc/sys/net/netfilter/nf_conntrack_count
  register: nf_conntrack

- name: remove nf_conntrack sysconf
  lineinfile:
    path: /etc/sysctl.conf
    regexp: "^net.netfilter.nf_conntrack_tcp_timeout_established"
    state: absent

- name: change nf_conntrack buckets
  file:
    path: /etc/modprobe.d/nf_conntrack.conf
    state: touch
  when: nf_conntrack.stat.exists == true

- name: change /etc/modprobe.d/nf_conntrack.conf
  lineinfile:
    path: /etc/modprobe.d/nf_conntrack.conf
    line: "options nf_conntrack hashsize=262144"
    regexp: "^options nf_conntrack hashsize="
    state: present
  when: nf_conntrack.stat.exists == true

- name: reboot after nf_conntrack changed
  shell: reboot now
  when: nf_conntrack.stat.exists == true

- name: refresh iptables
  shell: iptables -F