- name: disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: close selinux
  shell: setenforce 0 || true

- name: disable selinux
  lineinfile:
    state: present
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=disabled

- name: rm -rf /tmp/keepalived
  shell: rm -rf /tmp/keepalived

- name: mkdir /tmp/keepalived
  shell: mkdir -p /tmp/keepalived

- name: cp keepalived
  copy:
    src: '{{ package_dir }}/keepalived/'
    dest: /tmp/keepalived/

- name: install keepalived
  shell: yum localinstall -y /tmp/keepalived/*.rpm

- name: replace keepalived.conf
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf

- name: create keepalived dir
  file:
    path: '{{ keepalived_root_dir }}'
    state: directory

- name: query gateway address
  shell: grep "GATEWAY=" /etc/sysconfig/network-scripts/ifcfg-eth0
  register: gatewayline

- name: install health check script
  vars:
    gateway_addr: '{{ gatewayline.stdout.split("=")[1] }}'
  template:
    src: '{{ health_check_local_script }}.j2'
    dest: '{{ keepalived_root_dir }}/{{ health_check_local_script }}'
    mode: 0744

- name: copy keepalived.service
  template:
    src: keepalived.service
    dest: /usr/lib/systemd/system/keepalived.service

- name: start Keepalived
  systemd:
    name: keepalived
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: remove cron shell
  lineinfile:
    path: /var/spool/cron/root
    line: "{{ item }}"
    state: absent
  with_items:
    - "#Ansible: keepalived"
    - "*/1 * * * * /data01/keepalived/keepalived_cron.sh"

- name: remove /data01/keepalived/keepalived_cron.sh
  file:
    path: /data01/keepalived/keepalived_cron.sh
    state: absent