- name: disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: close selinux
  shell: setenforce 0 || true

- name: disable selinux
  lineinfile:
    state: present
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=disabled

- name: rm -rf /tmp/keepalived
  shell: rm -rf /tmp/keepalived

- name: mkdir /tmp/keepalived
  shell: mkdir -p /tmp/keepalived

- name: cp keepalived
  copy:
    src: '{{ package_dir }}/keepalived/'
    dest: /tmp/keepalived/

- name: install keepalived
  shell: yum localinstall -y /tmp/keepalived/*.rpm

- name: replace keepalived.conf
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf

- name: create keepalived dir
  file:
    path: '{{ keepalived_root_dir }}'
    state: directory

- name: install health check script
  copy:
    src: '{{ health_check_local_script }}'
    dest: '{{ keepalived_root_dir }}/{{ health_check_local_script }}'
    mode: 0744

- name: install cron for keepalived
  copy:
    src: keepalived_cron.sh
    dest: '{{ keepalived_root_dir }}/keepalived_cron.sh'
    mode: 0770

- name: stop keepalived
  shell: systemctl stop keepalived

- name: start Keepalived
  shell: systemctl restart keepalived && systemctl enable keepalived

- name: add cron for keepalived
  cron:
    name: keepalived
    minute: "*/1"
    job: '{{ keepalived_root_dir }}/keepalived_cron.sh'