- name: close selinux
  shell: /sbin/setenforce 0
  ignore_errors: True

- name: sed selinux
  shell: sed -i '/^SELINUX=/s/enforcing/disabled/' /etc/selinux/config

- name: close firewalld
  shell: systemctl stop firewalld &&  systemctl disable firewalld

- name: rm -rf /tmp/keepalived
  shell: rm -rf /tmp/keepalived

- name: mkdir /tmp/keepalived
  shell: mkdir -p /tmp/keepalived
  
- name: cp keepalived
  copy:
    src: '{{ package_dir }}/keepalived/'
    dest: /tmp/keepalived/

- name: install keepalived 
  shell: yum localinstall -y /tmp/keepalived/*.rpm

- name: replace keepalived.conf
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf

- name: create keepalived dir
  file:
    path: '{{ keepalived_root_dir }}'
    state: directory

- name: install health check script
  copy:
    src: '{{ health_check_local_script }}'
    dest: '{{ keepalived_root_dir }}/{{ health_check_local_script }}'
    mode: 0744

- name: install cron for keepalived
  copy:
    src: keepalived_cron.sh
    dest: '{{ keepalived_root_dir }}/keepalived_cron.sh'
    mode: 0770

- name: chown keepalived dir
  file:
    path: '{{ keepalived_root_dir }}'
    owner: '{{ cim_ops_user }}'
    recurse: yes

- name: stop keepalived
  shell: systemctl stop keepalived

- name: start Keepalived
  shell: sudo systemctl restart keepalived && systemctl enable keepalived

- name: add cron for keepalived
  cron:
    minute: "*/1"
    job: '{{ keepalived_root_dir }}/keepalived_cron.sh'
    user: '{{ cim_ops_user }}'
