- name: check has installed
  stat: path={{ kafka_root_dir }}
  register: p
- name: stop kafka
  command: docker-compose down
  args:
    chdir: "{{ kafka_root_dir }}"
  when: p.stat.isdir is defined and p.stat.isdir
- name: remove kafka data and other files
  command: "rm -rf {{ kafka_root_dir }}"
  when: p.stat.isdir is defined and p.stat.isdir
