- name: check has installed
  stat: path={{ es_root_dir }}
  register: p
- name: stop elasticsearch
  command: docker-compose down
  args:
    chdir: "{{ es_root_dir }}"
  when: p.stat.isdir is defined and p.stat.isdir
- name: remove elasticsearch data and other files
  command: "rm -rf {{ es_root_dir }}"
  when: p.stat.isdir is defined and p.stat.isdir