- name: check has installed
  stat: path=/etc/keepalived
  register: p

- name: rm -rf /tmp/keepalived
  shell: rm -rf /tmp/keepalived

- name: stop keepalived
  command: systemctl stop keepalived
  when: p.stat.isdir is defined and p.stat.isdir
  ignore_errors: yes

- name: unregister keepalived service
  command: systemctl disable keepalived
  when: p.stat.isdir is defined and p.stat.isdir
  ignore_errors: yes

- name: yum remove keepalived
  command: yum remove -y keepalived

- name: remove keepalived.conf
  command: rm -rf /etc/keepalived/