- name: create filebeat omm dir
  file:
    path: '/data01/filebeat/omm'
    state: directory

- name: create filebeat omm3 dir
  file:
    path: '/data01/filebeat/omm3'
    state: directory

- name: send omm docker-compose yaml
  template:
    src: 'docker-compose-omm.yml'
    dest: /data01/filebeat/omm/docker-compose.yml

- name: send omm3 docker-compose yaml
  template:
    src: 'docker-compose-omm3.yml'
    dest: /data01/filebeat/omm3/docker-compose.yml

- name: send filebeat conf
  template:
    src: 'filebeat-omm.yml'
    dest: /data01/filebeat/omm/filebeat.yml

- name: send filebeat conf
  template:
    src: 'filebeat-omm3.yml'
    dest: /data01/filebeat/omm3/filebeat.yml

- name: start omm filebeat
  shell: docker-compose down && docker-compose up -d
  args:
    chdir: /data01/filebeat/omm

- name: start omm3 filebeat
  shell: docker-compose down && docker-compose up -d
  args:
    chdir: /data01/filebeat/omm3