- name: create filebeat package temp dir
  file:
    path: /tmp/filebeat
    state: directory

- name: copy filebeat package
  copy:
    src: '{{ package_dir }}/filebeat/filebeat-7.13.2-x86_64.rpm'
    dest: /tmp/filebeat

- name: install filebeat
  shell: rpm -ivh filebeat-7.13.2-x86_64.rpm --replacepkgs --nodeps --force
  args:
    chdir: /tmp/filebeat

- name: stop filebeat
  systemd:
    name: filebeat
    state: stopped