- name: create filebeat alarm dir
  file:
    path: '/data01/filebeat/alarm'
    state: directory

- name: create filebeat check dir
  file:
    path: '/data01/filebeat/check'
    state: directory

- name: send alarm docker-compose yaml
  template:
    src: 'docker-compose-alarm.yml.j2'
    dest: /data01/filebeat/alarm/docker-compose.yml

- name: send check docker-compose yaml
  template:
    src: 'docker-compose-check.yml.j2'
    dest: /data01/filebeat/check/docker-compose.yml

- name: send filebeat conf
  template:
    src: 'filebeat-alarm.yml.j2'
    dest: /data01/filebeat/alarm/filebeat.yml

- name: send filebeat conf
  template:
    src: 'filebeat-check.yml.j2'
    dest: /data01/filebeat/check/filebeat.yml

- name: start alarm filebeat
  shell: docker-compose down && docker-compose up -d
  args:
    chdir: /data01/filebeat/alarm

- name: start check filebeat
  shell: docker-compose down && docker-compose up -d
  args:
    chdir: /data01/filebeat/check