apiVersion: v1
kind: Service
metadata:
  name: plantu-mes-service-uat
  namespace: plantu
  annotations:
    # 没有开放http服务，则使用tcp进行存活性探测
    prometheus.io/tcp-probe: "true"
    # jmx指标抓取的路径
    prometheus.io/scrape: "true"
    prometheus.io/port: '9998'
    prometheus.io/scheme: "http"
    prometheus.io/path: '/'
spec:
  ports:
    #   提供http服务的这么配置
    - name: http
      # 服务端口号，spring boot的应用可以直接用默认的8080
      port: 8383
      targetPort: 8383
  selector:
    # 此处不需要加zone的label，所以双机房可以共用一个service
    app: plantu-mes-uat
  ports:
    # 应用的端口号，用于上方tcp探测
    - port: 29096
  type: NodePort
