kind: Service
apiVersion: v1
metadata:
  name: rms-ui
  namespace: rms
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: rms-ui
  sessionAffinity: None
  type: ClusterIP