- name: check has installed
  stat: path={{ elk_manifest_root_dir }}
  register: p
- name: delete filebeat logstash kibana
  command: kubectl delete -f {{ elk_manifest_root_dir }}
  args:
    chdir: "{{ elk_manifest_root_dir }}"
  when: p.stat.isdir is defined and p.stat.isdir
- name: remove manifest files
  command: "rm -rf {{ elk_manifest_root_dir }}"
  when: p.stat.isdir is defined and p.stat.isdir
