apiVersion: v1
kind: Namespace
metadata:
  name: gaussdb-monitoring
---
apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: change-timezone
  namespace: gaussdb-monitoring
spec:
  selector:
    matchLabels: {}
  env:
    - name: TZ
      value: "Asia/Shanghai"
  volumeMounts:
    - name: timezone
      mountPath: /etc/localtime
  volumes:
    - name: timezone
      hostPath:
        path: /etc/localtime
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gaussdb-monitoring-admin
  namespace: gaussdb-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gaussdb-monitoring-admin-rolebinding
  namespace: gaussdb-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: gaussdb-monitoring-admin
    namespace: gaussdb-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gaussdb-monitoring-admin-view-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view-namespaces
subjects:
  - kind: ServiceAccount
    name: gaussdb-monitoring-admin
    namespace: gaussdb-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gaussdb-monitoring-admin-view-crd-resources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view-crd-resources
subjects:
  - kind: ServiceAccount
    name: gaussdb-monitoring-admin
    namespace: gaussdb-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: crd-object-admin
  namespace: gaussdb-monitoring
rules:
  - verbs:
      - create
      - delete
      - update
    apiGroups:
      - '*'
    resources:
      - ingressroutes
      - ingressroutetcps
      - ingressrouteudps
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - '*'
    resources:
      - ingressroutes
      - ingressroutetcps
      - ingressrouteudps
      - middlewares
      - servicemonitors
      - alertmanagers
      - prometheusrules
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gaussdb-monitoring-crd-object-admin
  namespace: gaussdb-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: crd-object-admin
subjects:
  - kind: ServiceAccount
    name: gaussdb-monitoring-admin
    namespace: gaussdb-monitoring