apiVersion: v1
kind: Service
metadata:
  name: kube-controller-manager
  namespace: kube-system
  annotations:
    maintainer: tangjizhou@cicem.fa
  labels:
    k8s-app: kube-controller-manager
spec:
  selector:
    component: kube-controller-manager
  ports:
    - name: http-metrics
      port: 10257
---
apiVersion: v1
kind: Service
metadata:
  name: kube-scheduler
  namespace: kube-system
  annotations:
    maintainer: tangjizhou@cicem.fa
  labels:
    k8s-app: kube-scheduler
spec:
  selector:
    component: kube-scheduler
  ports:
    - name: http-metrics
      port: 10259