apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: prometheus-adapter
  name: prometheus-adapter
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: https
    scheme: https
    relabelings:
      - action: replace
        sourceLabels: [ __meta_kubernetes_service_annotation_maintainer ]
        targetLabel: maintainer
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      name: prometheus-adapter
