apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: traefik-rules
  namespace: monitoring
spec:
  groups:
    - name: traefik
      rules:
        - alert: TraefikServiceDown
          expr: absent(up{service="traefik"} == 1) OR up{service="traefik"} == 0
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: Traefik service down (instance {{ $labels.instance }})
            description: "All Traefik services are down.  VALUE = {{ $value }}"
        - alert: TraefikHighHttp5xxErrorRateService
          expr: sum(rate(traefik_service_requests_total{code=~"5.*"}[3m])) by (service) / sum(rate(traefik_service_requests_total[3m])) by (service) * 100 > 5
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: Traefik high HTTP 5xx error rate service (instance {{ $labels.instance }})
            description: "Traefik service 5xx error rate is above 5%.  VALUE = {{ $value }}"
