apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: app-rules
  namespace: monitoring
spec:
  groups:
    - name: GaleraAlerts
      rules:
        - alert: ConsumerFallingBehind
          expr: (sum(rocketmq_producer_offset) by (topic) - on(topic)  group_right  sum(rocketmq_consumer_offset) by (group,topic)) - ignoring(group) group_left sum (avg_over_time(rocketmq_producer_tps[5m])) by (topic)*5*60 > 0
          for: 3m
          labels:
            severity: warning
          annotations:
            description: 'Rocketmq Topic {{$labels.topic}}消费者组{{$labels.group}}消费滞后，滞后值{{$value}}.'
            summary: Rocketmq消费者滞后
        - alert: GroupGetLatencyByStoretime
          expr: rocketmq_group_get_latency_by_storetime > 10000
          for: 3m
          labels:
            severity: warning
          annotations:
            description: 'Rocketmq节点{{$labels.broker}} 的Topic {{$labels.topic}}的消费者组{{$labels.group}}消息消费时间落后于消息生产实践太长，当前值{{$value}})
            summary: 消息消费时间落后于生产时间太长