apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: redis-rules
  namespace: monitoring
spec:
  groups:
    - name: redis
      rules:
        - alert: RedisDown
          expr: redis_up == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: Redis服务异常
            description: "Redis {{ $labels.instance }}服务异常"
        - alert: RedisMissingMaster
          expr: (count(redis_instance_info{role="master"}) or vector(0)) < 3
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: Redis集群Master节点过少
            description: "Redis集群Master节点过少，当前Master个数 {{ $value }}"
        - alert: RedisTooManyMasters
          expr: count(redis_instance_info{role="master"}) > 3
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: Redis集群Master节点过多
            description: "Redis集群Master节点过多，当前Master个数 {{ $value }}"
        - alert: RedisDisconnectedSlaves
          expr: count without (instance, job) (redis_connected_slaves) - sum without (instance, job) (redis_connected_slaves) > 3
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: Redis集群存在从节点失联
            description: "Redis集群存在从节点失联，当前从节点数{{ $value }}"
        - alert: RedisClusterFlapping
          expr: changes(redis_connected_slaves[1m]) > 1
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: Redis集群震荡
            description: "Redis {{ $labels.instance }}主从连接发生变化。当集群主从节点断开并重新连接时会发生此类情况。"
        - alert: RedisMissingBackup
          expr: time() - redis_rdb_last_save_timestamp_seconds > 60 * 60 * 24
          for: 30m
          labels:
            severity: critical
          annotations:
            summary: Redis未备份
            description: "Redis {{ $labels.instance }}超过24小时没有备份"
        # The exporter must be started with --include-system-metrics flag or REDIS_EXPORTER_INCL_SYSTEM_METRICS=true environment variable.
        - alert: RedisOutOfSystemMemory
          expr: redis_memory_used_bytes / redis_total_system_memory_bytes * 100 > 90
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: Redis内存占用过高
            description: "Redis {{ $labels.instance }}内存占用超过系统的90%，当前{{ $value }}"
        - alert: RedisOutOfConfiguredMaxmemory
          expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 90
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: Redis内存占用过高 (instance {{ $labels.instance }})
            description: "Redis {{ $labels.instance }}内存占用超过配置内存的90%，当前{{ $value }}"
        - alert: RedisTooManyConnections
          # maxclients 50000
          expr: redis_connected_clients > 45000
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: Redis连接数过多
            description: "Redis节点{{ $labels.instance }}连接数过多。最大值50000，当前连接数{{ $value }}"
        - alert: RedisRejectedConnections
          expr: increase(redis_rejected_connections_total[1m]) > 0
          for: 0m
          labels:
            severity: critical
          annotations:
            summary: Redis节点出现拒绝连接
            description: "Redis节点{{ $labels.instance }}拒绝了部分连接"






