apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: kafka-rules
  namespace: monitoring
spec:
  groups:
    - name: kafka
      rules:
        - alert: KafkaTopicsReplicas
          expr: sum(kafka_topic_partition_in_sync_replica) by (topic, instance) < 3
          for: 3m
          labels:
            severity: critical
          annotations:
            summary: Kafka的Topic分区备份数量太少
            description: "Kafka {{ $labels.instance }}的Topic分区同步数量太少，Topic {{ $labels.topic }}，同步数量{{ $value }}"
        - alert: KafkaConsumersGroup
          expr: sum(kafka_consumergroup_lag) by (consumergroup, instance) > 500000
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: Kafka消息组消费滞后(instance {{ $labels.instance }})
            description: "Kafka {{ $labels.instance }}的消费组{{ $labels.consumergroup }}消费滞后，消息积压数{{ $value }}"

