apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: ravencast-rules
  namespace: monitoring
spec:
  groups:
    - name: ravencast
      rules:
        - alert: RavencastAgentDown
          expr: up{service=~"ravencast.*"} == 0
          for: 30s
          labels:
            severity: critical
          annotations:
            summary: Ravencast服务不可用
            description: "服务{{ $labels.service }}的ravencast {{ $labels.instance }}服务不可用"
        - alert: RavencastLicenseExpiring
          expr: ravencast_expire_days_total{} < 60
          for: 0m
          labels:
            severity: warning
          annotations:
            summary: Ravencast证书即将过期
            description: "服务{{ $labels.service }}的ravencast {{ $labels.instance }}证书即将在{{ $value }}天后过期"
        - alert: RavencastQueueWait
          expr: ravencast_queue_wait_count_total{} > 2000
          for: 3m
          labels:
            severity: warning
          annotations:
            summary: Ravencast消息积压,current {{ $value }}  (service {{ $labels.service }})
            description: "服务{{ $labels.service }}的ravencast {{ $labels.instance }}消息积压过多，当前积压数{{ $value }}"
