apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: app-rules
  namespace: monitoring
spec:
  groups:
    - name: GaleraAlerts
      rules:
        - alert: ConsumerFallingBehind
          expr: (sum(rocketmq_producer_offset) by (topic) - on(topic)  group_right  sum(rocketmq_consumer_offset) by (group,topic)) - ignoring(group) group_left sum (avg_over_time(rocketmq_producer_tps[5m])) by (topic)*5*60 > 0
          for: 3m
          labels:
            severity: warning
          annotations:
            description: 'consumer {{$labels.group}} on {{$labels.topic}} lag behind
          and is falling behind (behind value {{$value}}).'
            summary: consumer lag behind
        - alert: GroupGetLatencyByStoretime
          expr: rocketmq_group_get_latency_by_storetime{topic != "BenchmarkTest"} > 10000
          for: 3m
          labels:
            severity: warning
          annotations:
            description: 'consumer {{$labels.group}} on {{$labels.broker}}, {{$labels.topic}} consume time lag behind message store time
          and (behind value is {{$value}}).'
            summary: message consumes time lag behind message store time too much