- name: create dir
  file:
    path: "{{ component_manifest_dir }}/app"
    state: directory

- name: copy app manifest template
  template:
    src: '{{ item.src }}'
    dest: "{{ component_manifest_dir }}/app/{{ item.path | regex_replace('\\.j2$', '') }}"
  with_filetree: templates/
  when: item.state == 'file'

- name: copy app manifest file
  synchronize:
    src: files/
    dest: "{{ component_manifest_dir }}/app/"