apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
  generation: 1
  managedFields:
    - apiVersion: traefik.containo.us/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          .: {}
          f:entryPoints: {}
          f:routes: {}
      manager: kubectl-client-side-apply
      operation: Update
  name: {{ .Values.name }}
  namespace: {{ .Values.nameSpace }}
  uid: ffbe1f6b-824b-450b-a5be-228bb357ace9
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ .Values.Host}}`)&&PathPrefix(`{{ .Values.PathPrefix}}`)
      services:
        - name: {{ .Values.name }}
          port: 80

