---
- name: config docker daemon
  shell: mkdir -p /etc/docker/

- name: config docker daemon
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json

- name: daemon-reload
  shell: systemctl daemon-reload

- name: restart docker 
  shell: systemctl restart docker