- name: create dirs
  shell: mkdir -p {{ rocketmq_root_dir }}/logs

- name: send rocketmq to remote
  unarchive:
    src: "{{ rocketmq_package_dir }}/rocketmq-all-4.7.1-bin-release.tar.gz"
    dest: "{{ rocketmq_root_dir }}"

- name: replace rocketmq manager script
  template:
    src: rmq-tools.sh.j2
    dest: "{{ rocketmq_root_dir }}/bin/rmq-tools.sh"
    mode: 0755

- name: set mq env conf
  lineinfile:
    dest: /etc/profile
    line: "{{ item }}"
  with_items:
    - "export RMQ_BIN={{ rocketmq_root_dir }}/bin"
    - "export PATH=$RMQ_BIN:$PATH"
    - "export ROCKETMQ_HOME={{ rocketmq_root_dir }}"

- name: enable profile
  shell: source /etc/profile

- name: mq-user permission
  file:
    path: '{{ rocketmq_root_dir }}'
    owner: '{{ rocketmq_user }}'
    recurse: yes

- name: rotate rockemq logs
  template:
    src: rocketmq.j2
    dest: /etc/logrotate.d/rocketmq

- name: start mq
  become: yes
  become_user: "{{ rocketmq_user }}"
  shell: "{{ rocketmq_root_dir }}/bin/rmq-tools.sh namesrv restart"

- name: add auto start rocketmq namesrv when bootstrap
  lineinfile:
    line: "{{ rocketmq_root_dir }}/bin/rmq-tools.sh namesrv start"
    path: /etc/rc.d/rc.local
    state: present
    mode: 0774

- name: add cron job
  cron:
    user: '{{ rocketmq_user }}'
    minute: '*/2'
    job: '{{ rocketmq_root_dir }}/bin/rmq-tools.sh namesrv start'