apiVersion: v1
data: {}
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
      smtp_smarthost: '192.168.160.1:587'
      smtp_from: 'mouyongde@huawei.com'
      smtp_require_tls: false
      smtp_auth_username: 'mouyongde@huawei.com'
      smtp_auth_password: 'Huawei@777.com'
    route:
      group_by:
        - namespace
        - alertname
        - severity
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: default
    receivers:
      - name: default
        email_configs:
          - to: tangjizhou@huawei.com
            send_resolved: true
type: Opaque
