version: '3'
services:
  coredns:
    image: 192.168.160.47:8888/google_containers/coredns:1.6.7
    network_mode: host
    restart: always
    command:
      - -conf
      - /etc/coredns/Corefile
    expose:
      - '53'
      - '53/udp'
    ports:
      - '53:53'
      - '53:53/udp'
    volumes:
      - ./conf:/etc/coredns