apiVersion: apps/v1
kind: Deployment
metadata:
  name: ams-data-dc1
  namespace: ams
  labels:
    zone: dc1
    app: ams-data
spec:
  replicas: 1
  template:
    metadata:
      name: ams-data-dc1
      labels:
        zone: dc1
        app: ams-data
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - ams-data
      nodeSelector:
        zone: dc1
      initContainers:
        - name: setsysctl
          command:
            - sysctl
            - -w
            - net.ipv4.tcp_keepalive_time=10
            - net.ipv4.tcp_keepalive_probes=2
            - net.ipv4.tcp_keepalive_intvl=5
          image: 192.168.160.47:8888/public/busybox:1.34
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
      containers:
        - name: ams-data
          image: 192.168.160.47:8888/ams/amsdata:v0
          imagePullPolicy: IfNotPresent
          startupProbe:
            httpGet:
              port: 8105
              path: /metrics
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              port: 8105
              path: /metrics
            timeoutSeconds: 1
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              port: 8105
              path: /metrics
          resources:
            limits:
              cpu: '4'
              memory: 8Gi
            requests:
              cpu: '0.2'
              memory: 1Gi
          lifecycle:
            preStop:
              exec:
                command: [ "sleep" ,"40" ]
      terminationGracePeriodSeconds: 120
      restartPolicy: Always
      imagePullSecrets:
        - name: harbor
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 2
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 2
  selector:
    matchLabels:
      zone: dc1
      app: ams-data