apiVersion: apps/v1
kind: Deployment
metadata:
  name: ams-api-dc1
  namespace: ams
  labels:
    zone: dc1
    app: ams-api
spec:
  replicas: 1
  template:
    metadata:
      name: ams-api
      labels:
        app: ams-api
        zone: dc1
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - ams-api
      nodeSelector:
        zone: dc1
      initContainers:
        - name: setsysctl
          command:
            - sysctl
            - -w
            - net.ipv4.tcp_keepalive_time=10
            - net.ipv4.tcp_keepalive_probes=2
            - net.ipv4.tcp_keepalive_intvl=5
          image: 192.168.160.47:8888/public/busybox:1.34
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
      containers:
        - name: ams-api
          image: 192.168.160.47:8888/ams/amsapi:v0
          imagePullPolicy: IfNotPresent
          startupProbe:
            httpGet:
              port: 8100
              path: /ams/health/get
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: 8100
              path: /ams/health/get
            timeoutSeconds: 1
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              port: 8100
              path: /ams/health/get
          resources:
            limits:
              cpu: '4'
              memory: 8Gi
            requests:
              cpu: '0.5'
              memory: 1Gi
          lifecycle:
            preStop:
              exec:
                command: [ "sleep" ,"40" ]
      terminationGracePeriodSeconds: 120
      restartPolicy: Always
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 2
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 2
  selector:
    matchLabels:
      zone: dc1
      app: ams-api
---
apiVersion: v1
kind: Service
metadata:
  name: ams-api
  namespace: ams
spec:
  selector:
    app: ams-api
  ports:
    - port: 8100
      nodePort: 30377
  type: NodePort
