---
kind: Service
apiVersion: v1
metadata:
  name: apc-algorithm-service
  namespace: pcs

spec:
  ports:
    - protocol: TCP
      port: 11005
      targetPort: 11005
  selector:
    app: apc-algorithm-service
  type: ClusterIP
  sessionAffinity: None
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: apc-algorithm-service
  namespace: pcs
  labels:
    app: apc-algorithm-service

spec:
  replicas: 2
  selector:
    matchLabels:
      app: apc-algorithm-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apc-algorithm-service
    spec:
      volumes:
        - name: tz-config
          hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
      containers:
        - name: apc-algorithm-service
          image: $app.image$
          env:
            - name: QIANDAO_AI_PROFILE
              value: product
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: tz-config
            mountPath: /etc/localtime
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: regcred
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - apc-algorithm-service
                topologyKey: kubernetes.io/hostname
      schedulerName: default-scheduler
      tolerations:
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 2
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600    
status:
  observedGeneration: 5
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2021-12-03T07:39:30Z'
      lastTransitionTime: '2021-12-03T07:39:30Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2021-12-06T07:33:09Z'
      lastTransitionTime: '2021-12-03T07:31:55Z'
      reason: NewReplicaSetAvailable
      message: >-
        ReplicaSet "apc-algorithm-service-df6477955" has successfully
        progressed.
