---
apiVersion: v1
kind: Service
metadata:
  name: apc-ui-web
  namespace: pcs
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: apc-ui-web
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: apc-ui-web
  namespace: pcs
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`pcs-uat.cicem.fa`) && PathPrefix(`/apc/`)
      kind: Rule
      services:
        - name: apc-ui-web
          port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apc-ui-web
  namespace: pcs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apc-ui-web
  template:
    metadata:
      labels:
        app: apc-ui-web
        zone: dc1
    spec:
      imagePullSecrets:
        - name: regcred
      # 节点失活后，该节点的 pod 2s后进行迁移，
      # k8s集群检测node down掉40s后，将node状态置为not-ready，
      # 再过2s，该节点pod会重新迁移到其他节点
      hostNetwork: false
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 2
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 2
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - apc-ui-web
              weight: 100
      nodeSelector:
        zone: dc1
      volumes:
        - name: tz-config
          hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
      containers:
        - name: apc-ui-web
          image: $IMAGE$
          imagePullPolicy: Always
          volumeMounts:
          - name: tz-config
            mountPath: /etc/localtime
          ports:
            - containerPort: 80
          # 存活性探针 和 准备就绪探针
          resources:
            limits:
              cpu: "2"
              memory: 2048Mi
            requests:
              cpu: 50m
              memory: 100Mi
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 300
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10