---
apiVersion: v1
kind: Service
metadata:
  name: workflow-runtime-service
  namespace: pcs
  annotations:
    prometheus.io/http-probe: "true"
    prometheus.io/http-probe-port: "true"
    prometheus.io/http-probe-path: "/workflow-runtime/flower/health/check"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/scheme: "http"
    prometheus.io/path: "/workflow-runtime/actuator/prometheus"
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: workflow-runtime-service
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: workflow-runtime-service
  namespace: pcs
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/workflow-runtime`) && Host(`pcs-uat.cicem.fa`)
      services:
        - name: workflow-runtime-service
          port: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: pcs
  labels:
    k8s-app: workflow-runtime-service
data:
  filebeat.yml: |-
    filebeat.inputs:
      - type: log
        enabled: true
        paths:
          -  /data/workflow/logs/runtime/flow.log
        json.keys_under_root: true
        tags: ["apc_flow_log"]
        fields:
          index: 'apc-flow-log'
      - type: log
        enabled: true
        paths:
          -  /data/workflow/logs/runtime/node.log
        json.keys_under_root: true
        tags: ["apc_flow_node_log"]
        fields:
          index: 'apc-flow-node-log'

    output.elasticsearch:
      hosts: ["$OUT_PUT_ES_HOST$"]
      indices:
        - index: "apc-flow-log"
          when.contains:
            fields:
              index: 'apc-flow-log'
        - index: "apc-flow-node-log"
          when.contains:
            fields:
              index: 'apc-flow-node-log'          
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-runtime-service
  namespace: pcs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow-runtime-service
      zone: dc1
  template:
    metadata:
      labels:
        app: workflow-runtime-service
        zone: dc1
    spec:
        - name: data
          emptyDir: {}
        - name: logdata
          emptyDir: {}
        - name: config
          configMap:
            name: filebeat-config
            items:
              - key: filebeat.yml
                path: filebeat.yml
            defaultMode: 420
      imagePullSecrets:
        - name: regcred
      # 节点失活后，该节点的 pod 2s后进行迁移，
      # k8s集群检测node down掉40s后，将node状态置为not-ready，
      # 再过2s，该节点pod会重新迁移到其他节点
      hostNetwork: false
      # 增加反亲和性调度,pod调度到不同node
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - workflow-runtime-service
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 2
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 2
      nodeSelector:
        zone: dc1
      initContainers:
        - command:
          - sysctl
          - -w
          - net.ipv4.tcp_keepalive_time=10
          - net.ipv4.tcp_keepalive_probes=2
          - net.ipv4.tcp_keepalive_intvl=5
          image: 10.12.107.150:80/public/busybox:1.34
          imagePullPolicy: Always
          name: setsysctl
          securityContext:
            privileged: true  
      volumes:
        - name: tz-config
          hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai          
      containers:
        - name: workflow-runtime-service
          image: $IMAGE$
          imagePullPolicy: Always
          volumeMounts:
          - name: tz-config
            mountPath: /etc/localtime
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod_i"
            - name: SERVER_PORT
              value: "8080"
            - name: DB_HOST
              value: "$DB_HOST$"
            - name: DB_PORT
              value: "$DB_PORT$"
            - name: DB_USER
              value: "$DB_USER$"
            - name: DB_PWD
              value: "$DB_PWD$"
            - name: REDIS_NODES
              value: "$REDIS_NODES$"
            - name: REDIS_PWD
              value: "$REDIS_PWD$"
            - name: ES_HOST
              value: "$ES_HOST$"
            - name: ES_PORT
              value: "$ES_PORT$"
            - name: ROCKETMQ_NODES
              value: "$ROCKETMQ_NODES$"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "2"
              memory: 2048Mi
            requests:
              cpu: "0.5"
              memory: 1024Mi
          volumeMounts:
            - name: logdata
              mountPath: /data
          # 存活性探针 和 准备就绪探针
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /workflow-runtime/flower/health/check
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 300
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 20
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /workflow-runtime/flower/health/check
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
            name: filebeat
            image: '$ELASTIC_IMAGE$'
            args:
              - '-c'
              - /opt/filebeat/filebeat.yml
              - '-e'
            env:
              - name: POD_IP
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: status.podIP
              - name: pod_name
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.name
            resources:
              limits:
                memory: 200Mi
              requests:
                cpu: 100m
                memory: 100Mi
            volumeMounts:
              - name: config
                mountPath: /opt/filebeat/
              - name: data
                mountPath: /usr/share/filebeat/data
              - name: logdata
                mountPath: /data
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: IfNotPresent
            securityContext:
              runAsUser: 0