---
apiVersion: v1
kind: Service
metadata:
  name: workflow-portal-service
  namespace: pcs
  annotations:
    prometheus.io/http-probe: "true"
    prometheus.io/http-probe-port: "true"
    prometheus.io/http-probe-path: "/workflow-portal/apc/wf-proc-def/health/check"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/scheme: "http"
    prometheus.io/path: "/workflow-portal/actuator/prometheus"
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: workflow-portal-service
---
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: workflow-portal-service
  namespace: pcs
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/workflow-portal`) && Host(`pcs-uat.cicem.fa`)
      services:
        - name: workflow-portal-service
          port: 8080    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-portal-service
  namespace: pcs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow-portal-service
      zone: dcl
  template:
    metadata:
      labels:
        app: workflow-portal-service
        zone: dcl
    spec:
      volumes:
        - name: data
          emptyDir: {}
        - name: logdata
          emptyDir: {}
        - name: config
          configMap:
            name: filebeat-portal-config
            items:
              - key: filebeat.yml
                path: filebeat.yml
            defaultMode: 420
        - name: tz-config
          hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
      imagePullSecrets:
        - name: regcred
      # 节点失活后，该节点的 pod 2s后进行迁移，
      # k8s集群检测node down掉40s后，将node状态置为not-ready，
      # 再过2s，该节点pod会重新迁移到其他节点
      hostNetwork: false
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 2
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 2
      nodeSelector:
        zone: dc1
      initContainers:
        - command:
          - sysctl
          - -w
          - net.ipv4.tcp_keepalive_time=10
          - net.ipv4.tcp_keepalive_probes=2
          - net.ipv4.tcp_keepalive_intvl=5
          image: 10.12.107.150:80/public/busybox:1.34
          imagePullPolicy: Always
          name: setsysctl
          securityContext:
            privileged: true 
      containers:
        - name: workflow-portal-service
          image: $IMAGE$
          imagePullPolicy: Always
          volumeMounts:
          - name: tz-config
            mountPath: /etc/localtime
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod_i"
            - name: SERVER_PORT
              value: "8080"
            - name: DB_HOST
              value: "$DB_HOST$"
            - name: DB_PORT
              value: "15400"
            - name: DB_USER
              value: "$DB_USER$"
            - name: DB_PWD
              value: "$DB_PWD$"
            - name: REDIS_NODES
              value: "$REDIS_NODES$"
            - name: REDIS_PWD
              value: "$REDIS_PWD$"
            - name: ES_HOST
              value: "$ES_HOST$"
            - name: ES_PORT
              value: "9200"
            - name: ROCKETMQ_NODES
              value: "$ROCKETMQ_NODES$"
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+UseG1GC -XX:MaxRAMPercentage=75.0"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "2"
              memory: 2048Mi
            requests:
              cpu: "0.2"
              memory: 500Mi
          # 存活性探针 和 准备就绪探针
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /workflow-portal/apc/wf-proc-def/health/check
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 300
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 20
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /workflow-portal/apc/wf-proc-def/health/check
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          - name: filebeat
            image: 'docker.elastic.co/beats/filebeat:7.9.2'
            args:
              - '-c'
              - /opt/filebeat/filebeat.yml
              - '-e'
            env:
              - name: POD_IP
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: status.podIP
              - name: pod_name
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.name
            resources:
              limits:
                memory: 200Mi
              requests:
                cpu: 100m
                memory: 100Mi
            volumeMounts:
              - name: config
                mountPath: /opt/filebeat/
              - name: data
                mountPath: /usr/share/filebeat/data
              - name: logdata
                mountPath: /data
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: IfNotPresent
            securityContext:
              runAsUser: 0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-portal-config
  namespace: pcs
  labels:
    k8s-app: workflow-portal-service
data:
  filebeat.yml: |-
    filebeat.inputs:
      - type: log
        enabled: true
        paths:
          -  /data/workflow/logs/portal/flow-quartz.log
        json.keys_under_root: true
        tags: ["apc_flow_quartz_log"]
        fields:
          index: 'apc-flow-quartz-log'

    output.elasticsearch:
      hosts: ["10.247.13.168:9200"]
      indices:
        - index: "apc-flow-quartz-log"
          when.contains:
            fields:
              index: 'apc-flow-quartz-log'