- name: ensure jdk dir exist
  file:
    path: "{{ jdk_dir }}"
    state: directory
    mode: 0755

- name: unzip jdk tar
  unarchive: 
    src: "{{ package_dir }}/jdk/jdk-8u202-linux-x64.tar.gz"
    dest: "{{ jdk_dir }}"

- name: set java env conf
  lineinfile:
    dest: /etc/profile
    state: present
    line: "{{ item }}"
  with_items:
    - "export JAVA_HOME={{ jdk_dir }}"
    - "export JRE_HOME=${JAVA_HOME}/jre"
    - "export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib"
    - "export PATH=${JAVA_HOME}/bin:$PATH"
    
- name: java profile enable
  shell: source /etc/profile

- name: set java env conf ~/.bashrc
  lineinfile:
    dest: ~/.bashrc
    state: present
    line: "{{ item }}"
  with_items:
    - "export JAVA_HOME={{ jdk_dir }}"
    - "export JRE_HOME=${JAVA_HOME}/jre"
    - "export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib"
    - "export PATH=${JAVA_HOME}/bin:$PATH"
