- name: create dirs
  shell: |
    mkdir -p {{ rocketmq_root_dir }}
    mkdir -p {{ rocketmq_root_dir }}/logs
    mkdir -p {{ rocketmq_root_dir }}/conf/2m-2s-sync
    rm -rf {{ rocketmq_root_dir }}/conf/2m-2s-sync/*.properties

- name: send rocketmq to remote
  unarchive:
    src: "{{ rocketmq_package_dir }}/rocketmq-all-4.7.1-bin-release.tar.gz"
    dest: "{{ rocketmq_root_dir }}"

- name: send rocketmq master conf
  template:
    src: broker-m.properties.j2
    dest: "{{ rocketmq_root_dir }}/conf/2m-2s-sync/{{ broker_name }}.properties"

- name: replace rocketmq manager script
  template:
    src: rmq-tools.sh.j2
    dest: "{{ rocketmq_root_dir }}/bin/rmq-tools.sh"
    owner: "{{ rocketmq_user }}"
    mode: '0755'

- name: set mq env conf
  lineinfile:
    dest: /etc/profile
    line: "{{ item }}"
  with_items:
    - "export RMQ_BIN={{ rocketmq_root_dir }}/bin"
    - "export PATH=$RMQ_BIN:$PATH"
    - "export ROCKETMQ_HOME={{ rocketmq_root_dir }}"

- name: enable profile
  shell: source /etc/profile

- name: mq-user permission
  shell: |
    chown -R {{ rocketmq_user }} {{ rocketmq_root_dir }}
    chmod -R 760 {{ rocketmq_root_dir }}
    chown -R {{ rocketmq_user }} {{rocketmq_root_dir}}

- name: start mq
  become_user: "{{ rocketmq_user }}"
  shell: "{{ rocketmq_root_dir }}/bin/rmq-tools.sh {{ broker_name }} restart"

- name: rotate rockemq logs
  template:
    src: rocketmq.j2
    dest: /etc/logrotate.d/rocketmq

- name: add cron job
  cron:
    user: '{{ rocketmq_user }}'
    minute: '*'
    job: '{{ rocketmq_root_dir }}/bin/rmq-tools.sh {{ broker_name }} start'