---
- name: rm -rf /data01/harbor
  shell: rm -rf /data01/harbor

- name: mkdir /data01/harbor
  shell: mkdir -p /data01/harbor

- name: unarchive harbor
  unarchive: src=/etc/ansible/rpms/harbor/harbor-offline-installer-v2.1.0.tgz dest=/data01
 
- name: copy harbor.yml
  template: src=harbor.yml.j2 dest=/data01/harbor/harbor.yml
 
- name: copy install-me.sh
  template: src=install-me.sh.j2 dest=/data01/harbor/install-me.sh

- name: chmod +x install-me.sh
  shell: systemctl restart docker

- name: chmod +x install-me.sh
  shell: chmod +x install-me.sh
  args:
   chdir: /data01/harbor

- name: install
  shell: "./install-me.sh"
  args:
   chdir: "/data01/harbor"

- name: cp harbor service
  template: src=harbor.service.j2 dest=/usr/lib/systemd/system/harbor.service

- name: enable harbor service
  shell: systemctl enable harbor.service


