- name: modify sysctl
  lineinfile:
    dest: /etc/sysctl.conf
    line: "{{ item }}"
  with_items:
    - "vm.overcommit_memory = 1"

- name: sysctl enable
  shell: sysctl -p /etc/sysctl.conf

- name: create root dir
  file:
    path: '{{ kafka_root_dir }}'
    state: directory

- name: install with docker compose
  template: src=docker-compose.yml.j2 dest={{ kafka_root_dir }}/docker-compose.yml

- name: create container volums
  command: mkdir -p {{ kafka_root_dir }}/zookeeper/conf {{ kafka_root_dir }}/zookeeper/data {{ kafka_root_dir }}/zookeeper/datalog

- name: chmod dir
  command: chmod -R a+rwx {{ kafka_root_dir }}/zookeeper/conf {{ kafka_root_dir }}/zookeeper/data {{ kafka_root_dir }}/zookeeper/datalog

- name: shutdown kafka
  command: docker-compose -f {{ kafka_root_dir }}/docker-compose.yml down

- name: start up kafka
  command: docker-compose -f {{ kafka_root_dir }}/docker-compose.yml up -d

- name: wait kafak ready
  wait_for:
    port: 9092
    delay: 20
    timeout: 60
    msg: 'Timeout waiting for kafka respond'

- name: create topic
  command: docker-compose exec -T kafka kafka-topics.sh --zookeeper localhost:2181 --create --topic test --partitions 5 --replication-factor 1
  args:
    chdir: "{{ kafka_root_dir }}"
  register: create_result
  when: ansible_ssh_host == groups['kafka'][0]

- name: show result
  debug:
    msg: "{{ create_result.stdout }}"
  when: ansible_ssh_host == groups['kafka'][0]

- name: list topic
  command: docker-compose exec -T kafka  kafka-topics.sh  --zookeeper localhost:2181 --list
  args:
    chdir: "{{ kafka_root_dir }}"
  register: list_result
  when: ansible_ssh_host == groups['kafka'][0]

- name: show result
  debug:
    msg: "{{ list_result.stdout }}"
  when: ansible_ssh_host == groups['kafka'][0]

- name: assert list result
  assert:
    that:
      - "'test' in list_result.stdout_lines"
  when: ansible_ssh_host == groups['kafka'][0]
