- name: create root dir
  command: mkdir -p {{ kafka_root_dir }}

- name: install with docker compose
  template: src=docker-compose.yml.j2 dest={{ kafka_root_dir }}/docker-compose.yml

- name: create container volums
  command: mkdir -p {{ kafka_root_dir }}/zookeeper/conf {{ kafka_root_dir }}/zookeeper/data {{ kafka_root_dir }}/zookeeper/datalog

- name: chmod dir
  command: chmod -R a+rwx {{ kafka_root_dir }}/zookeeper/conf {{ kafka_root_dir }}/zookeeper/data {{ kafka_root_dir }}/zookeeper/datalog

- name: chown jenkins dir
  file:
    path: '{{ kafka_root_dir }}'
    owner: '{{ cim_ops_user }}'
    group: docker
    recurse: yes

- name: shutdown kafka
  become_user: '{{ cim_ops_user }}'
  command: docker-compose -f {{ kafka_root_dir }}/docker-compose.yml down

- name: start up kafka
  become_user: '{{ cim_ops_user }}'
  command: docker-compose -f {{ kafka_root_dir }}/docker-compose.yml up -d

- name: pause
  command: sleep 30

- name: create topic
  become_user: '{{ cim_ops_user }}'
  command: docker-compose exec -T kafka kafka-topics.sh --zookeeper localhost:2181 --create --topic test --partitions 5 --replication-factor 1
  args:
    chdir: "{{ kafka_root_dir }}"
  register: create_result
  when: ansible_ssh_host == groups['kafka'][0]
  ignore_errors: yes

- name: show result
  debug:
    msg: "{{ create_result.stdout }}"
  when: ansible_ssh_host == groups['kafka'][0]

- name: list topic
  become_user: '{{ cim_ops_user }}'
  command: docker-compose exec -T kafka  kafka-topics.sh  --zookeeper localhost:2181 --list
  args:
    chdir: "{{ kafka_root_dir }}"
  register: list_result
  when: ansible_ssh_host == groups['kafka'][0]

- name: show result
  debug:
    msg: "{{ list_result.stdout }}"
  when: ansible_ssh_host == groups['kafka'][0]

- name: assert list result
  assert:
    that:
      - "{{ list_result.stdout == 'test' }}"
  when: ansible_ssh_host == groups['kafka'][0]

- name: pause
  command: sleep 10
  when: ansible_ssh_host == groups['kafka'][0]
