- name: clear old dir
  command: rm -rf {{ root_dir }}
- name: create root dir
  command: mkdir -p {{ root_dir }}
- name: install with docker compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ root_dir }}/docker-compose.yml"
- name: showdown kafka
  command: docker-compose -f {{ root_dir }}/docker-compose.yml down
- name: create container volums
  command: mkdir -p {{ root_dir }}/zookeeper/conf {{ root_dir }}/zookeeper/data {{ root_dir }}/zookeeper/datalog
- name: chmod dir
  command: chmod -R a+rwx {{ root_dir }}/zookeeper/conf {{ root_dir }}/zookeeper/data {{ root_dir }}/zookeeper/datalog
- name: start up kafka
  command: docker-compose -f {{ root_dir }}/docker-compose.yml up -d