- name: create agent root dir
  file:
    path: '{{ gaussdb_monitor_agent_root_dir }}/{{ gaussdb_user }}'
    state: directory

- name: create wsr dir
  file:
    path: /wsr
    state: directory
    owner: '{{ gaussdb_user }}'
    group: '{{ gaussdb_user_group }}'

- name: send agent application.yml
  template:
    src: agent/application.yml.j2
    dest: '{{ gaussdb_monitor_agent_root_dir }}/{{ gaussdb_user }}/application.yml'

- name: send agent jar
  copy:
    src: agent/hisi-uoamp-monitor-agent-1.0-SNAPSHOT.jar
    dest: '{{ gaussdb_monitor_agent_root_dir }}/{{ gaussdb_user }}/agent.jar'

- name: chmod agent dir
  file:
    path: '{{ gaussdb_monitor_agent_root_dir }}/{{ gaussdb_user }}'
    state: directory
    owner: '{{ gaussdb_user }}'
    group: '{{ gaussdb_user_group }}'
    recurse: yes

- name: copy gaussdb agent startup shell
  template:
    src: start-agent.sh.j2
    dest: '{{ gaussdb_monitor_agent_root_dir }}/{{ gaussdb_user }}/start-agent.sh'

- name: create cron job for db agent
  become_user: '{{ gaussdb_user }}'
  become: yes
  cron:
    name: gaussdb agent job
    job: '{{ gaussdb_monitor_agent_root_dir }}/{{ gaussdb_user }}/start-agent.sh'
    minute: "*/1"

- name: start gaussdb agent systemd service
  systemd:
    name: gaussdb-agent
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: send filebeat.yml
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml