- name: create agent root dir
  file:
    path: '{{ gaussdb_monitor_agent_root_dir }}/{{ gaussdb_user }}'
    state: directory
    owner: '{{ gaussdb_user }}'
    group: '{{ gaussdb_user_group }}'

- name: create wsr dir
  file:
    path: /wsr
    state: directory
    owner: '{{ gaussdb_user }}'
    group: '{{ gaussdb_user_group }}'

- name: send agent application.yml
  template:
    src: agent/application.yml.j2
    dest: '{{ gaussdb_monitor_agent_root_dir }}/{{ gaussdb_user }}/application.yml'
    owner: '{{ gaussdb_user }}'
    group: '{{ gaussdb_user_group }}'

- name: send agent jar
  copy:
    src: agent/hisi-uoamp-monitor-agent-1.0-SNAPSHOT.jar
    dest: '{{ gaussdb_monitor_agent_root_dir }}/{{ gaussdb_user }}/agent.jar'
    owner: '{{ gaussdb_user }}'
    group: '{{ gaussdb_user_group }}'

# fixme 为啥启动不成功？
- name: start agent
  shell: "su {{ gaussdb_user }} &&  nohup java -jar {{ gaussdb_monitor_agent_root_dir }}/{{ gaussdb_user }}/agent.jar > /dev/null 2>&1 &"
