- name: remove env
  lineinfile:
    dest: /etc/profile
    state: absent
    line: "{{ item }}"
  with_items:
    - "export JAVA_HOME={{ jdk_dir }}"
    - "export JRE_HOME=${JAVA_HOME}/jre"
    - "export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib"
    - "export PATH=${JAVA_HOME}/bin:$PATH"

- name: java profile enable
  shell: source /etc/profile

- name: remove jdk dir
  command: "rm -rf {{ jdk_dir }}"