
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plantumes-admin
  namespace: plantu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plantumes-admin
  template:
    metadata:
      labels:
        app: plantumes-admin
    spec:
      imagePullSecrets:
        - name: harbor
      hostNetwork: false
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 2
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 2
      containers:
        - name: plantumes-admin
          image: 10.12.107.150:80/plantu-prod/plantu-mes-admin-h:v1.0.6
          # 当前服务器已经存在相同版本的镜像则不会重复拉取
          imagePullPolicy: IfNotPresent
          startupProbe:
            httpGet:
              path: /heartbeat
              port: 8282
              scheme: HTTP
            successThreshold: 1
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /heartbeat
              port: 8282
              scheme: HTTP
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /heartbeat
              port: 8282
              scheme: HTTP
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 3
            periodSeconds: 5
          # 容器启动端口，没有可以删除
          # 容器资源，request表示分配的最小资源，limit表示分配的资源上限
          resources:
            limits:
              cpu: "2"
              memory: 16384Mi
            requests:
              cpu: "1"
              memory: 8192Mi
          # 优雅关机，需要确保基础镜像要有/bin/bash命令
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/bash", "-c", "sleep 30" ]
        - name: plantu-agent
          image: 10.12.107.150:80/plantu-prod/plantu-mes-agent:v1.0.3
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: prod-agent-mes
              mountPath: /PlantUMes/Agent/config
      volumes:
        - name: prod-agent-mes
          configMap:
            name: prod-agent-mes
      # k8s给程序发kill -9的时间，这时间需要大于preStop的时间
      terminationGracePeriodSeconds: 60
